// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLogHTTPParams creates a new GetLogHTTPParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLogHTTPParams() *GetLogHTTPParams {
	return &GetLogHTTPParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogHTTPParamsWithTimeout creates a new GetLogHTTPParams object
// with the ability to set a timeout on a request.
func NewGetLogHTTPParamsWithTimeout(timeout time.Duration) *GetLogHTTPParams {
	return &GetLogHTTPParams{
		timeout: timeout,
	}
}

// NewGetLogHTTPParamsWithContext creates a new GetLogHTTPParams object
// with the ability to set a context for a request.
func NewGetLogHTTPParamsWithContext(ctx context.Context) *GetLogHTTPParams {
	return &GetLogHTTPParams{
		Context: ctx,
	}
}

// NewGetLogHTTPParamsWithHTTPClient creates a new GetLogHTTPParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLogHTTPParamsWithHTTPClient(client *http.Client) *GetLogHTTPParams {
	return &GetLogHTTPParams{
		HTTPClient: client,
	}
}

/*
GetLogHTTPParams contains all the parameters to send to the API endpoint

	for the get log HTTP operation.

	Typically these are written to a http.Request.
*/
type GetLogHTTPParams struct {

	/* OrderBy.

	   Order by field
	*/
	OrderBy *string

	/* OrderDirection.

	   'asc' or 'desc' for ascending or descending order
	*/
	OrderDirection *string

	/* Page.

	   page number
	*/
	Page *int64

	/* PageSize.

	   number of entities per page
	*/
	PageSize *int64

	/* Search.

	   searchable value in entity
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get log HTTP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogHTTPParams) WithDefaults() *GetLogHTTPParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get log HTTP params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogHTTPParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get log HTTP params
func (o *GetLogHTTPParams) WithTimeout(timeout time.Duration) *GetLogHTTPParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get log HTTP params
func (o *GetLogHTTPParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get log HTTP params
func (o *GetLogHTTPParams) WithContext(ctx context.Context) *GetLogHTTPParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get log HTTP params
func (o *GetLogHTTPParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get log HTTP params
func (o *GetLogHTTPParams) WithHTTPClient(client *http.Client) *GetLogHTTPParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get log HTTP params
func (o *GetLogHTTPParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrderBy adds the orderBy to the get log HTTP params
func (o *GetLogHTTPParams) WithOrderBy(orderBy *string) *GetLogHTTPParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get log HTTP params
func (o *GetLogHTTPParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrderDirection adds the orderDirection to the get log HTTP params
func (o *GetLogHTTPParams) WithOrderDirection(orderDirection *string) *GetLogHTTPParams {
	o.SetOrderDirection(orderDirection)
	return o
}

// SetOrderDirection adds the orderDirection to the get log HTTP params
func (o *GetLogHTTPParams) SetOrderDirection(orderDirection *string) {
	o.OrderDirection = orderDirection
}

// WithPage adds the page to the get log HTTP params
func (o *GetLogHTTPParams) WithPage(page *int64) *GetLogHTTPParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get log HTTP params
func (o *GetLogHTTPParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get log HTTP params
func (o *GetLogHTTPParams) WithPageSize(pageSize *int64) *GetLogHTTPParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get log HTTP params
func (o *GetLogHTTPParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithSearch adds the search to the get log HTTP params
func (o *GetLogHTTPParams) WithSearch(search *string) *GetLogHTTPParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get log HTTP params
func (o *GetLogHTTPParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogHTTPParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.OrderBy != nil {

		// query param orderBy
		var qrOrderBy string

		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {

			if err := r.SetQueryParam("orderBy", qOrderBy); err != nil {
				return err
			}
		}
	}

	if o.OrderDirection != nil {

		// query param orderDirection
		var qrOrderDirection string

		if o.OrderDirection != nil {
			qrOrderDirection = *o.OrderDirection
		}
		qOrderDirection := qrOrderDirection
		if qOrderDirection != "" {

			if err := r.SetQueryParam("orderDirection", qOrderDirection); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
