// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// GetLogHTTPReader is a Reader for the GetLogHTTP structure.
type GetLogHTTPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLogHTTPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLogHTTPOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetLogHTTPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLogHTTPOK creates a GetLogHTTPOK with default headers values
func NewGetLogHTTPOK() *GetLogHTTPOK {
	return &GetLogHTTPOK{}
}

/*
GetLogHTTPOK describes a response with status code 200, with default header values.

OK
*/
type GetLogHTTPOK struct {
	Payload *models.DtosPaginatedItemsDtoDtosHTTPLogDto
}

// IsSuccess returns true when this get log Http o k response has a 2xx status code
func (o *GetLogHTTPOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get log Http o k response has a 3xx status code
func (o *GetLogHTTPOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get log Http o k response has a 4xx status code
func (o *GetLogHTTPOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get log Http o k response has a 5xx status code
func (o *GetLogHTTPOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get log Http o k response a status code equal to that given
func (o *GetLogHTTPOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetLogHTTPOK) Error() string {
	return fmt.Sprintf("[GET /log/http/][%d] getLogHttpOK  %+v", 200, o.Payload)
}

func (o *GetLogHTTPOK) String() string {
	return fmt.Sprintf("[GET /log/http/][%d] getLogHttpOK  %+v", 200, o.Payload)
}

func (o *GetLogHTTPOK) GetPayload() *models.DtosPaginatedItemsDtoDtosHTTPLogDto {
	return o.Payload
}

func (o *GetLogHTTPOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosPaginatedItemsDtoDtosHTTPLogDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLogHTTPInternalServerError creates a GetLogHTTPInternalServerError with default headers values
func NewGetLogHTTPInternalServerError() *GetLogHTTPInternalServerError {
	return &GetLogHTTPInternalServerError{}
}

/*
GetLogHTTPInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetLogHTTPInternalServerError struct {
}

// IsSuccess returns true when this get log Http internal server error response has a 2xx status code
func (o *GetLogHTTPInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get log Http internal server error response has a 3xx status code
func (o *GetLogHTTPInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get log Http internal server error response has a 4xx status code
func (o *GetLogHTTPInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get log Http internal server error response has a 5xx status code
func (o *GetLogHTTPInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get log Http internal server error response a status code equal to that given
func (o *GetLogHTTPInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetLogHTTPInternalServerError) Error() string {
	return fmt.Sprintf("[GET /log/http/][%d] getLogHttpInternalServerError ", 500)
}

func (o *GetLogHTTPInternalServerError) String() string {
	return fmt.Sprintf("[GET /log/http/][%d] getLogHttpInternalServerError ", 500)
}

func (o *GetLogHTTPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
