// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// GetLogAppReader is a Reader for the GetLogApp structure.
type GetLogAppReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetLogAppReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetLogAppOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetLogAppInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetLogAppOK creates a GetLogAppOK with default headers values
func NewGetLogAppOK() *GetLogAppOK {
	return &GetLogAppOK{}
}

/*
GetLogAppOK describes a response with status code 200, with default header values.

OK
*/
type GetLogAppOK struct {
	Payload *models.DtosPaginatedItemsDtoDtosAppLogDto
}

// IsSuccess returns true when this get log app o k response has a 2xx status code
func (o *GetLogAppOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get log app o k response has a 3xx status code
func (o *GetLogAppOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get log app o k response has a 4xx status code
func (o *GetLogAppOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get log app o k response has a 5xx status code
func (o *GetLogAppOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get log app o k response a status code equal to that given
func (o *GetLogAppOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetLogAppOK) Error() string {
	return fmt.Sprintf("[GET /log/app/][%d] getLogAppOK  %+v", 200, o.Payload)
}

func (o *GetLogAppOK) String() string {
	return fmt.Sprintf("[GET /log/app/][%d] getLogAppOK  %+v", 200, o.Payload)
}

func (o *GetLogAppOK) GetPayload() *models.DtosPaginatedItemsDtoDtosAppLogDto {
	return o.Payload
}

func (o *GetLogAppOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosPaginatedItemsDtoDtosAppLogDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetLogAppInternalServerError creates a GetLogAppInternalServerError with default headers values
func NewGetLogAppInternalServerError() *GetLogAppInternalServerError {
	return &GetLogAppInternalServerError{}
}

/*
GetLogAppInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetLogAppInternalServerError struct {
}

// IsSuccess returns true when this get log app internal server error response has a 2xx status code
func (o *GetLogAppInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get log app internal server error response has a 3xx status code
func (o *GetLogAppInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get log app internal server error response has a 4xx status code
func (o *GetLogAppInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get log app internal server error response has a 5xx status code
func (o *GetLogAppInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get log app internal server error response a status code equal to that given
func (o *GetLogAppInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetLogAppInternalServerError) Error() string {
	return fmt.Sprintf("[GET /log/app/][%d] getLogAppInternalServerError ", 500)
}

func (o *GetLogAppInternalServerError) String() string {
	return fmt.Sprintf("[GET /log/app/][%d] getLogAppInternalServerError ", 500)
}

func (o *GetLogAppInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
