// Code generated by go-swagger; DO NOT EDIT.

package log

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLogHTTPIDParams creates a new GetLogHTTPIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLogHTTPIDParams() *GetLogHTTPIDParams {
	return &GetLogHTTPIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogHTTPIDParamsWithTimeout creates a new GetLogHTTPIDParams object
// with the ability to set a timeout on a request.
func NewGetLogHTTPIDParamsWithTimeout(timeout time.Duration) *GetLogHTTPIDParams {
	return &GetLogHTTPIDParams{
		timeout: timeout,
	}
}

// NewGetLogHTTPIDParamsWithContext creates a new GetLogHTTPIDParams object
// with the ability to set a context for a request.
func NewGetLogHTTPIDParamsWithContext(ctx context.Context) *GetLogHTTPIDParams {
	return &GetLogHTTPIDParams{
		Context: ctx,
	}
}

// NewGetLogHTTPIDParamsWithHTTPClient creates a new GetLogHTTPIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLogHTTPIDParamsWithHTTPClient(client *http.Client) *GetLogHTTPIDParams {
	return &GetLogHTTPIDParams{
		HTTPClient: client,
	}
}

/*
GetLogHTTPIDParams contains all the parameters to send to the API endpoint

	for the get log HTTP ID operation.

	Typically these are written to a http.Request.
*/
type GetLogHTTPIDParams struct {

	/* ID.

	   log id
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get log HTTP ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogHTTPIDParams) WithDefaults() *GetLogHTTPIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get log HTTP ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogHTTPIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get log HTTP ID params
func (o *GetLogHTTPIDParams) WithTimeout(timeout time.Duration) *GetLogHTTPIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get log HTTP ID params
func (o *GetLogHTTPIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get log HTTP ID params
func (o *GetLogHTTPIDParams) WithContext(ctx context.Context) *GetLogHTTPIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get log HTTP ID params
func (o *GetLogHTTPIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get log HTTP ID params
func (o *GetLogHTTPIDParams) WithHTTPClient(client *http.Client) *GetLogHTTPIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get log HTTP ID params
func (o *GetLogHTTPIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get log HTTP ID params
func (o *GetLogHTTPIDParams) WithID(id string) *GetLogHTTPIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get log HTTP ID params
func (o *GetLogHTTPIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogHTTPIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
