// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// GetTemplateDeviceNameReader is a Reader for the GetTemplateDeviceName structure.
type GetTemplateDeviceNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTemplateDeviceNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTemplateDeviceNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetTemplateDeviceNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTemplateDeviceNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetTemplateDeviceNameOK creates a GetTemplateDeviceNameOK with default headers values
func NewGetTemplateDeviceNameOK() *GetTemplateDeviceNameOK {
	return &GetTemplateDeviceNameOK{}
}

/*
GetTemplateDeviceNameOK describes a response with status code 200, with default header values.

OK
*/
type GetTemplateDeviceNameOK struct {
	Payload *models.DtosDeviceTemplateDto
}

// IsSuccess returns true when this get template device name o k response has a 2xx status code
func (o *GetTemplateDeviceNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get template device name o k response has a 3xx status code
func (o *GetTemplateDeviceNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template device name o k response has a 4xx status code
func (o *GetTemplateDeviceNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get template device name o k response has a 5xx status code
func (o *GetTemplateDeviceNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get template device name o k response a status code equal to that given
func (o *GetTemplateDeviceNameOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetTemplateDeviceNameOK) Error() string {
	return fmt.Sprintf("[GET /template/device/{name}][%d] getTemplateDeviceNameOK  %+v", 200, o.Payload)
}

func (o *GetTemplateDeviceNameOK) String() string {
	return fmt.Sprintf("[GET /template/device/{name}][%d] getTemplateDeviceNameOK  %+v", 200, o.Payload)
}

func (o *GetTemplateDeviceNameOK) GetPayload() *models.DtosDeviceTemplateDto {
	return o.Payload
}

func (o *GetTemplateDeviceNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosDeviceTemplateDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateDeviceNameNotFound creates a GetTemplateDeviceNameNotFound with default headers values
func NewGetTemplateDeviceNameNotFound() *GetTemplateDeviceNameNotFound {
	return &GetTemplateDeviceNameNotFound{}
}

/*
GetTemplateDeviceNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetTemplateDeviceNameNotFound struct {
}

// IsSuccess returns true when this get template device name not found response has a 2xx status code
func (o *GetTemplateDeviceNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template device name not found response has a 3xx status code
func (o *GetTemplateDeviceNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template device name not found response has a 4xx status code
func (o *GetTemplateDeviceNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get template device name not found response has a 5xx status code
func (o *GetTemplateDeviceNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get template device name not found response a status code equal to that given
func (o *GetTemplateDeviceNameNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetTemplateDeviceNameNotFound) Error() string {
	return fmt.Sprintf("[GET /template/device/{name}][%d] getTemplateDeviceNameNotFound ", 404)
}

func (o *GetTemplateDeviceNameNotFound) String() string {
	return fmt.Sprintf("[GET /template/device/{name}][%d] getTemplateDeviceNameNotFound ", 404)
}

func (o *GetTemplateDeviceNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetTemplateDeviceNameInternalServerError creates a GetTemplateDeviceNameInternalServerError with default headers values
func NewGetTemplateDeviceNameInternalServerError() *GetTemplateDeviceNameInternalServerError {
	return &GetTemplateDeviceNameInternalServerError{}
}

/*
GetTemplateDeviceNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetTemplateDeviceNameInternalServerError struct {
}

// IsSuccess returns true when this get template device name internal server error response has a 2xx status code
func (o *GetTemplateDeviceNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template device name internal server error response has a 3xx status code
func (o *GetTemplateDeviceNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template device name internal server error response has a 4xx status code
func (o *GetTemplateDeviceNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get template device name internal server error response has a 5xx status code
func (o *GetTemplateDeviceNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get template device name internal server error response a status code equal to that given
func (o *GetTemplateDeviceNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetTemplateDeviceNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /template/device/{name}][%d] getTemplateDeviceNameInternalServerError ", 500)
}

func (o *GetTemplateDeviceNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /template/device/{name}][%d] getTemplateDeviceNameInternalServerError ", 500)
}

func (o *GetTemplateDeviceNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
