// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/sadov/rolctl/models"
	"github.com/spf13/cobra"
)

// Schema cli for DtosHostNetworkBridgeCreateDto

// register flags to command
func registerModelDtosHostNetworkBridgeCreateDtoFlags(depth int, cmdPrefix string, cmd *cobra.Command) error {

	if err := registerDtosHostNetworkBridgeCreateDtoAddresses(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDtosHostNetworkBridgeCreateDtoName(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	if err := registerDtosHostNetworkBridgeCreateDtoSlaves(depth, cmdPrefix, cmd); err != nil {
		return err
	}

	return nil
}

func registerDtosHostNetworkBridgeCreateDtoAddresses(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: addresses []string array type is not supported by go-swagger cli yet

	return nil
}

func registerDtosHostNetworkBridgeCreateDtoName(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	nameDescription := `Name interface full name`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}

func registerDtosHostNetworkBridgeCreateDtoSlaves(depth int, cmdPrefix string, cmd *cobra.Command) error {
	if depth > maxDepth {
		return nil
	}

	// warning: slaves []string array type is not supported by go-swagger cli yet

	return nil
}

// retrieve flags from commands, and set value in model. Return true if any flag is passed by user to fill model field.
func retrieveModelDtosHostNetworkBridgeCreateDtoFlags(depth int, m *models.DtosHostNetworkBridgeCreateDto, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false

	err, addressesAdded := retrieveDtosHostNetworkBridgeCreateDtoAddressesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || addressesAdded

	err, nameAdded := retrieveDtosHostNetworkBridgeCreateDtoNameFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || nameAdded

	err, slavesAdded := retrieveDtosHostNetworkBridgeCreateDtoSlavesFlags(depth, m, cmdPrefix, cmd)
	if err != nil {
		return err, false
	}
	retAdded = retAdded || slavesAdded

	return nil, retAdded
}

func retrieveDtosHostNetworkBridgeCreateDtoAddressesFlags(depth int, m *models.DtosHostNetworkBridgeCreateDto, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	addressesFlagName := fmt.Sprintf("%v.addresses", cmdPrefix)
	if cmd.Flags().Changed(addressesFlagName) {
		// warning: addresses array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}

func retrieveDtosHostNetworkBridgeCreateDtoNameFlags(depth int, m *models.DtosHostNetworkBridgeCreateDto, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	nameFlagName := fmt.Sprintf("%v.name", cmdPrefix)
	if cmd.Flags().Changed(nameFlagName) {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

		retAdded = true
	}

	return nil, retAdded
}

func retrieveDtosHostNetworkBridgeCreateDtoSlavesFlags(depth int, m *models.DtosHostNetworkBridgeCreateDto, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	if depth > maxDepth {
		return nil, false
	}
	retAdded := false

	slavesFlagName := fmt.Sprintf("%v.slaves", cmdPrefix)
	if cmd.Flags().Changed(slavesFlagName) {
		// warning: slaves array type []string is not supported by go-swagger cli yet
	}

	return nil, retAdded
}
