// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/sadov/rolctl/client/ethernet_switch"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationEthernetSwitchGetEthernetSwitchCmd returns a cmd to handle operation getEthernetSwitch
func makeOperationEthernetSwitchGetEthernetSwitchCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetEthernetSwitch",
		Short: ``,
		RunE:  runOperationEthernetSwitchGetEthernetSwitch,
	}

	if err := registerOperationEthernetSwitchGetEthernetSwitchParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEthernetSwitchGetEthernetSwitch uses cmd flags to call endpoint api
func runOperationEthernetSwitchGetEthernetSwitch(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := ethernet_switch.NewGetEthernetSwitchParams()
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchOrderByFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchOrderDirectionFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchPageFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchPageSizeFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchSearchFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationEthernetSwitchGetEthernetSwitchResult(appCli.EthernetSwitch.GetEthernetSwitch(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationEthernetSwitchGetEthernetSwitchParamFlags registers all flags needed to fill params
func registerOperationEthernetSwitchGetEthernetSwitchParamFlags(cmd *cobra.Command) error {
	if err := registerOperationEthernetSwitchGetEthernetSwitchOrderByParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEthernetSwitchGetEthernetSwitchOrderDirectionParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEthernetSwitchGetEthernetSwitchPageParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEthernetSwitchGetEthernetSwitchPageSizeParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEthernetSwitchGetEthernetSwitchSearchParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationEthernetSwitchGetEthernetSwitchOrderByParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	orderByDescription := `Order by field, default value - Name`

	var orderByFlagName string
	if cmdPrefix == "" {
		orderByFlagName = "orderBy"
	} else {
		orderByFlagName = fmt.Sprintf("%v.orderBy", cmdPrefix)
	}

	var orderByFlagDefault string

	_ = cmd.PersistentFlags().String(orderByFlagName, orderByFlagDefault, orderByDescription)

	return nil
}
func registerOperationEthernetSwitchGetEthernetSwitchOrderDirectionParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	orderDirectionDescription := `'asc' or 'desc' for ascending or descending order, asc by default`

	var orderDirectionFlagName string
	if cmdPrefix == "" {
		orderDirectionFlagName = "orderDirection"
	} else {
		orderDirectionFlagName = fmt.Sprintf("%v.orderDirection", cmdPrefix)
	}

	var orderDirectionFlagDefault string

	_ = cmd.PersistentFlags().String(orderDirectionFlagName, orderDirectionFlagDefault, orderDirectionDescription)

	return nil
}
func registerOperationEthernetSwitchGetEthernetSwitchPageParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pageDescription := `Page number`

	var pageFlagName string
	if cmdPrefix == "" {
		pageFlagName = "page"
	} else {
		pageFlagName = fmt.Sprintf("%v.page", cmdPrefix)
	}

	var pageFlagDefault int64

	_ = cmd.PersistentFlags().Int64(pageFlagName, pageFlagDefault, pageDescription)

	return nil
}
func registerOperationEthernetSwitchGetEthernetSwitchPageSizeParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	pageSizeDescription := `Number of entities per page`

	var pageSizeFlagName string
	if cmdPrefix == "" {
		pageSizeFlagName = "pageSize"
	} else {
		pageSizeFlagName = fmt.Sprintf("%v.pageSize", cmdPrefix)
	}

	var pageSizeFlagDefault int64

	_ = cmd.PersistentFlags().Int64(pageSizeFlagName, pageSizeFlagDefault, pageSizeDescription)

	return nil
}
func registerOperationEthernetSwitchGetEthernetSwitchSearchParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	searchDescription := `Searchable value in entity`

	var searchFlagName string
	if cmdPrefix == "" {
		searchFlagName = "search"
	} else {
		searchFlagName = fmt.Sprintf("%v.search", cmdPrefix)
	}

	var searchFlagDefault string

	_ = cmd.PersistentFlags().String(searchFlagName, searchFlagDefault, searchDescription)

	return nil
}

func retrieveOperationEthernetSwitchGetEthernetSwitchOrderByFlag(m *ethernet_switch.GetEthernetSwitchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("orderBy") {

		var orderByFlagName string
		if cmdPrefix == "" {
			orderByFlagName = "orderBy"
		} else {
			orderByFlagName = fmt.Sprintf("%v.orderBy", cmdPrefix)
		}

		orderByFlagValue, err := cmd.Flags().GetString(orderByFlagName)
		if err != nil {
			return err, false
		}
		m.OrderBy = &orderByFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEthernetSwitchGetEthernetSwitchOrderDirectionFlag(m *ethernet_switch.GetEthernetSwitchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("orderDirection") {

		var orderDirectionFlagName string
		if cmdPrefix == "" {
			orderDirectionFlagName = "orderDirection"
		} else {
			orderDirectionFlagName = fmt.Sprintf("%v.orderDirection", cmdPrefix)
		}

		orderDirectionFlagValue, err := cmd.Flags().GetString(orderDirectionFlagName)
		if err != nil {
			return err, false
		}
		m.OrderDirection = &orderDirectionFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEthernetSwitchGetEthernetSwitchPageFlag(m *ethernet_switch.GetEthernetSwitchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("page") {

		var pageFlagName string
		if cmdPrefix == "" {
			pageFlagName = "page"
		} else {
			pageFlagName = fmt.Sprintf("%v.page", cmdPrefix)
		}

		pageFlagValue, err := cmd.Flags().GetInt64(pageFlagName)
		if err != nil {
			return err, false
		}
		m.Page = &pageFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEthernetSwitchGetEthernetSwitchPageSizeFlag(m *ethernet_switch.GetEthernetSwitchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("pageSize") {

		var pageSizeFlagName string
		if cmdPrefix == "" {
			pageSizeFlagName = "pageSize"
		} else {
			pageSizeFlagName = fmt.Sprintf("%v.pageSize", cmdPrefix)
		}

		pageSizeFlagValue, err := cmd.Flags().GetInt64(pageSizeFlagName)
		if err != nil {
			return err, false
		}
		m.PageSize = &pageSizeFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEthernetSwitchGetEthernetSwitchSearchFlag(m *ethernet_switch.GetEthernetSwitchParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("search") {

		var searchFlagName string
		if cmdPrefix == "" {
			searchFlagName = "search"
		} else {
			searchFlagName = fmt.Sprintf("%v.search", cmdPrefix)
		}

		searchFlagValue, err := cmd.Flags().GetString(searchFlagName)
		if err != nil {
			return err, false
		}
		m.Search = &searchFlagValue

	}
	return nil, retAdded
}

// parseOperationEthernetSwitchGetEthernetSwitchResult parses request result and return the string content
func parseOperationEthernetSwitchGetEthernetSwitchResult(resp0 *ethernet_switch.GetEthernetSwitchOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*ethernet_switch.GetEthernetSwitchOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getEthernetSwitchInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
