// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/sadov/rolctl/client/ethernet_switch"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationEthernetSwitchGetEthernetSwitchIDPortPortIDCmd returns a cmd to handle operation getEthernetSwitchIdPortPortId
func makeOperationEthernetSwitchGetEthernetSwitchIDPortPortIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "GetEthernetSwitchIDPortPortID",
		Short: ``,
		RunE:  runOperationEthernetSwitchGetEthernetSwitchIDPortPortID,
	}

	if err := registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEthernetSwitchGetEthernetSwitchIDPortPortID uses cmd flags to call endpoint api
func runOperationEthernetSwitchGetEthernetSwitchIDPortPortID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := ethernet_switch.NewGetEthernetSwitchIDPortPortIDParams()
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchIDPortPortIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEthernetSwitchGetEthernetSwitchIDPortPortIDPortIDFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationEthernetSwitchGetEthernetSwitchIDPortPortIDResult(appCli.EthernetSwitch.GetEthernetSwitchIDPortPortID(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDParamFlags registers all flags needed to fill params
func registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDPortIDParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Ethernet switch ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationEthernetSwitchGetEthernetSwitchIDPortPortIDPortIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	portIdDescription := `Required. Ethernet switch port ID`

	var portIdFlagName string
	if cmdPrefix == "" {
		portIdFlagName = "portID"
	} else {
		portIdFlagName = fmt.Sprintf("%v.portID", cmdPrefix)
	}

	var portIdFlagDefault string

	_ = cmd.PersistentFlags().String(portIdFlagName, portIdFlagDefault, portIdDescription)

	return nil
}

func retrieveOperationEthernetSwitchGetEthernetSwitchIDPortPortIDIDFlag(m *ethernet_switch.GetEthernetSwitchIDPortPortIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEthernetSwitchGetEthernetSwitchIDPortPortIDPortIDFlag(m *ethernet_switch.GetEthernetSwitchIDPortPortIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("portID") {

		var portIdFlagName string
		if cmdPrefix == "" {
			portIdFlagName = "portID"
		} else {
			portIdFlagName = fmt.Sprintf("%v.portID", cmdPrefix)
		}

		portIdFlagValue, err := cmd.Flags().GetString(portIdFlagName)
		if err != nil {
			return err, false
		}
		m.PortID = portIdFlagValue

	}
	return nil, retAdded
}

// parseOperationEthernetSwitchGetEthernetSwitchIDPortPortIDResult parses request result and return the string content
func parseOperationEthernetSwitchGetEthernetSwitchIDPortPortIDResult(resp0 *ethernet_switch.GetEthernetSwitchIDPortPortIDOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*ethernet_switch.GetEthernetSwitchIDPortPortIDOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning getEthernetSwitchIdPortPortIdNotFound is not supported

		// Non schema case: warning getEthernetSwitchIdPortPortIdInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
