// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/sadov/rolctl/client/dhcp"
	"github.com/sadov/rolctl/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDhcpPostDhcpIDLeaseCmd returns a cmd to handle operation postDhcpIdLease
func makeOperationDhcpPostDhcpIDLeaseCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PostDhcpIDLease",
		Short: ``,
		RunE:  runOperationDhcpPostDhcpIDLease,
	}

	if err := registerOperationDhcpPostDhcpIDLeaseParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDhcpPostDhcpIDLease uses cmd flags to call endpoint api
func runOperationDhcpPostDhcpIDLease(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dhcp.NewPostDhcpIDLeaseParams()
	if err, _ := retrieveOperationDhcpPostDhcpIDLeaseIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationDhcpPostDhcpIDLeaseRequestFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDhcpPostDhcpIDLeaseResult(appCli.Dhcp.PostDhcpIDLease(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDhcpPostDhcpIDLeaseParamFlags registers all flags needed to fill params
func registerOperationDhcpPostDhcpIDLeaseParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDhcpPostDhcpIDLeaseIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationDhcpPostDhcpIDLeaseRequestParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDhcpPostDhcpIDLeaseIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. DHCP v4 server ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationDhcpPostDhcpIDLeaseRequestParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var requestFlagName string
	if cmdPrefix == "" {
		requestFlagName = "request"
	} else {
		requestFlagName = fmt.Sprintf("%v.request", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(requestFlagName, "", "Optional json string for [request]. DHCP v4 lease fields")

	// add flags for body
	if err := registerModelDtosDHCP4LeaseCreateDtoFlags(0, "dtosDHCP4LeaseCreateDto", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationDhcpPostDhcpIDLeaseIDFlag(m *dhcp.PostDhcpIDLeaseParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationDhcpPostDhcpIDLeaseRequestFlag(m *dhcp.PostDhcpIDLeaseParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("request") {
		// Read request string from cmd and unmarshal
		requestValueStr, err := cmd.Flags().GetString("request")
		if err != nil {
			return err, false
		}

		requestValue := models.DtosDHCP4LeaseCreateDto{}
		if err := json.Unmarshal([]byte(requestValueStr), &requestValue); err != nil {
			return fmt.Errorf("cannot unmarshal request string in models.DtosDHCP4LeaseCreateDto: %v", err), false
		}
		m.Request = &requestValue
	}
	requestValueModel := m.Request
	if swag.IsZero(requestValueModel) {
		requestValueModel = &models.DtosDHCP4LeaseCreateDto{}
	}
	err, added := retrieveModelDtosDHCP4LeaseCreateDtoFlags(0, requestValueModel, "dtosDHCP4LeaseCreateDto", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Request = requestValueModel
	}
	if dryRun && debug {

		requestValueDebugBytes, err := json.Marshal(m.Request)
		if err != nil {
			return err, false
		}
		logDebugf("Request dry-run payload: %v", string(requestValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationDhcpPostDhcpIDLeaseResult parses request result and return the string content
func parseOperationDhcpPostDhcpIDLeaseResult(resp0 *dhcp.PostDhcpIDLeaseOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dhcp.PostDhcpIDLeaseOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*dhcp.PostDhcpIDLeaseBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning postDhcpIdLeaseInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
