// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/sadov/rolctl/client/host"
	"github.com/sadov/rolctl/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationHostPutHostNetworkBridgeNameCmd returns a cmd to handle operation putHostNetworkBridgeName
func makeOperationHostPutHostNetworkBridgeNameCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PutHostNetworkBridgeName",
		Short: ``,
		RunE:  runOperationHostPutHostNetworkBridgeName,
	}

	if err := registerOperationHostPutHostNetworkBridgeNameParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationHostPutHostNetworkBridgeName uses cmd flags to call endpoint api
func runOperationHostPutHostNetworkBridgeName(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := host.NewPutHostNetworkBridgeNameParams()
	if err, _ := retrieveOperationHostPutHostNetworkBridgeNameNameFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationHostPutHostNetworkBridgeNameRequestFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationHostPutHostNetworkBridgeNameResult(appCli.Host.PutHostNetworkBridgeName(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationHostPutHostNetworkBridgeNameParamFlags registers all flags needed to fill params
func registerOperationHostPutHostNetworkBridgeNameParamFlags(cmd *cobra.Command) error {
	if err := registerOperationHostPutHostNetworkBridgeNameNameParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationHostPutHostNetworkBridgeNameRequestParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationHostPutHostNetworkBridgeNameNameParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	nameDescription := `Required. Bridge name`

	var nameFlagName string
	if cmdPrefix == "" {
		nameFlagName = "name"
	} else {
		nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
	}

	var nameFlagDefault string

	_ = cmd.PersistentFlags().String(nameFlagName, nameFlagDefault, nameDescription)

	return nil
}
func registerOperationHostPutHostNetworkBridgeNameRequestParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var requestFlagName string
	if cmdPrefix == "" {
		requestFlagName = "request"
	} else {
		requestFlagName = fmt.Sprintf("%v.request", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(requestFlagName, "", "Optional json string for [request]. Host bridge fields")

	// add flags for body
	if err := registerModelDtosHostNetworkBridgeUpdateDtoFlags(0, "dtosHostNetworkBridgeUpdateDto", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationHostPutHostNetworkBridgeNameNameFlag(m *host.PutHostNetworkBridgeNameParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("name") {

		var nameFlagName string
		if cmdPrefix == "" {
			nameFlagName = "name"
		} else {
			nameFlagName = fmt.Sprintf("%v.name", cmdPrefix)
		}

		nameFlagValue, err := cmd.Flags().GetString(nameFlagName)
		if err != nil {
			return err, false
		}
		m.Name = nameFlagValue

	}
	return nil, retAdded
}
func retrieveOperationHostPutHostNetworkBridgeNameRequestFlag(m *host.PutHostNetworkBridgeNameParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("request") {
		// Read request string from cmd and unmarshal
		requestValueStr, err := cmd.Flags().GetString("request")
		if err != nil {
			return err, false
		}

		requestValue := models.DtosHostNetworkBridgeUpdateDto{}
		if err := json.Unmarshal([]byte(requestValueStr), &requestValue); err != nil {
			return fmt.Errorf("cannot unmarshal request string in models.DtosHostNetworkBridgeUpdateDto: %v", err), false
		}
		m.Request = &requestValue
	}
	requestValueModel := m.Request
	if swag.IsZero(requestValueModel) {
		requestValueModel = &models.DtosHostNetworkBridgeUpdateDto{}
	}
	err, added := retrieveModelDtosHostNetworkBridgeUpdateDtoFlags(0, requestValueModel, "dtosHostNetworkBridgeUpdateDto", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Request = requestValueModel
	}
	if dryRun && debug {

		requestValueDebugBytes, err := json.Marshal(m.Request)
		if err != nil {
			return err, false
		}
		logDebugf("Request dry-run payload: %v", string(requestValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationHostPutHostNetworkBridgeNameResult parses request result and return the string content
func parseOperationHostPutHostNetworkBridgeNameResult(resp0 *host.PutHostNetworkBridgeNameOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*host.PutHostNetworkBridgeNameOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*host.PutHostNetworkBridgeNameBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning putHostNetworkBridgeNameNotFound is not supported

		// Non schema case: warning putHostNetworkBridgeNameInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
