// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/sadov/rolctl/client/dhcp"
	"github.com/sadov/rolctl/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationDhcpPutDhcpIDLeaseLeaseIDCmd returns a cmd to handle operation putDhcpIdLeaseLeaseId
func makeOperationDhcpPutDhcpIDLeaseLeaseIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PutDhcpIDLeaseLeaseID",
		Short: ``,
		RunE:  runOperationDhcpPutDhcpIDLeaseLeaseID,
	}

	if err := registerOperationDhcpPutDhcpIDLeaseLeaseIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationDhcpPutDhcpIDLeaseLeaseID uses cmd flags to call endpoint api
func runOperationDhcpPutDhcpIDLeaseLeaseID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := dhcp.NewPutDhcpIDLeaseLeaseIDParams()
	if err, _ := retrieveOperationDhcpPutDhcpIDLeaseLeaseIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationDhcpPutDhcpIDLeaseLeaseIDLeaseIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationDhcpPutDhcpIDLeaseLeaseIDRequestFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationDhcpPutDhcpIDLeaseLeaseIDResult(appCli.Dhcp.PutDhcpIDLeaseLeaseID(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationDhcpPutDhcpIDLeaseLeaseIDParamFlags registers all flags needed to fill params
func registerOperationDhcpPutDhcpIDLeaseLeaseIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationDhcpPutDhcpIDLeaseLeaseIDIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationDhcpPutDhcpIDLeaseLeaseIDLeaseIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationDhcpPutDhcpIDLeaseLeaseIDRequestParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationDhcpPutDhcpIDLeaseLeaseIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. DHCP v4 server ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationDhcpPutDhcpIDLeaseLeaseIDLeaseIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	leaseIdDescription := `Required. DHCP v4 lease ID`

	var leaseIdFlagName string
	if cmdPrefix == "" {
		leaseIdFlagName = "leaseID"
	} else {
		leaseIdFlagName = fmt.Sprintf("%v.leaseID", cmdPrefix)
	}

	var leaseIdFlagDefault string

	_ = cmd.PersistentFlags().String(leaseIdFlagName, leaseIdFlagDefault, leaseIdDescription)

	return nil
}
func registerOperationDhcpPutDhcpIDLeaseLeaseIDRequestParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var requestFlagName string
	if cmdPrefix == "" {
		requestFlagName = "request"
	} else {
		requestFlagName = fmt.Sprintf("%v.request", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(requestFlagName, "", "Optional json string for [request]. DHCP v4 lease fields")

	// add flags for body
	if err := registerModelDtosDHCP4LeaseUpdateDtoFlags(0, "dtosDHCP4LeaseUpdateDto", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationDhcpPutDhcpIDLeaseLeaseIDIDFlag(m *dhcp.PutDhcpIDLeaseLeaseIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationDhcpPutDhcpIDLeaseLeaseIDLeaseIDFlag(m *dhcp.PutDhcpIDLeaseLeaseIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("leaseID") {

		var leaseIdFlagName string
		if cmdPrefix == "" {
			leaseIdFlagName = "leaseID"
		} else {
			leaseIdFlagName = fmt.Sprintf("%v.leaseID", cmdPrefix)
		}

		leaseIdFlagValue, err := cmd.Flags().GetString(leaseIdFlagName)
		if err != nil {
			return err, false
		}
		m.LeaseID = leaseIdFlagValue

	}
	return nil, retAdded
}
func retrieveOperationDhcpPutDhcpIDLeaseLeaseIDRequestFlag(m *dhcp.PutDhcpIDLeaseLeaseIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("request") {
		// Read request string from cmd and unmarshal
		requestValueStr, err := cmd.Flags().GetString("request")
		if err != nil {
			return err, false
		}

		requestValue := models.DtosDHCP4LeaseUpdateDto{}
		if err := json.Unmarshal([]byte(requestValueStr), &requestValue); err != nil {
			return fmt.Errorf("cannot unmarshal request string in models.DtosDHCP4LeaseUpdateDto: %v", err), false
		}
		m.Request = &requestValue
	}
	requestValueModel := m.Request
	if swag.IsZero(requestValueModel) {
		requestValueModel = &models.DtosDHCP4LeaseUpdateDto{}
	}
	err, added := retrieveModelDtosDHCP4LeaseUpdateDtoFlags(0, requestValueModel, "dtosDHCP4LeaseUpdateDto", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Request = requestValueModel
	}
	if dryRun && debug {

		requestValueDebugBytes, err := json.Marshal(m.Request)
		if err != nil {
			return err, false
		}
		logDebugf("Request dry-run payload: %v", string(requestValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationDhcpPutDhcpIDLeaseLeaseIDResult parses request result and return the string content
func parseOperationDhcpPutDhcpIDLeaseLeaseIDResult(resp0 *dhcp.PutDhcpIDLeaseLeaseIDOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*dhcp.PutDhcpIDLeaseLeaseIDOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*dhcp.PutDhcpIDLeaseLeaseIDBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning putDhcpIdLeaseLeaseIdNotFound is not supported

		// Non schema case: warning putDhcpIdLeaseLeaseIdInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
