// Code generated by go-swagger; DO NOT EDIT.

package cli

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"

	"github.com/sadov/rolctl/client/ethernet_switch"
	"github.com/sadov/rolctl/models"

	"github.com/go-openapi/swag"
	"github.com/spf13/cobra"
)

// makeOperationEthernetSwitchPutEthernetSwitchIDCmd returns a cmd to handle operation putEthernetSwitchId
func makeOperationEthernetSwitchPutEthernetSwitchIDCmd() (*cobra.Command, error) {
	cmd := &cobra.Command{
		Use:   "PutEthernetSwitchID",
		Short: ``,
		RunE:  runOperationEthernetSwitchPutEthernetSwitchID,
	}

	if err := registerOperationEthernetSwitchPutEthernetSwitchIDParamFlags(cmd); err != nil {
		return nil, err
	}

	return cmd, nil
}

// runOperationEthernetSwitchPutEthernetSwitchID uses cmd flags to call endpoint api
func runOperationEthernetSwitchPutEthernetSwitchID(cmd *cobra.Command, args []string) error {
	appCli, err := makeClient(cmd, args)
	if err != nil {
		return err
	}
	// retrieve flag values from cmd and fill params
	params := ethernet_switch.NewPutEthernetSwitchIDParams()
	if err, _ := retrieveOperationEthernetSwitchPutEthernetSwitchIDIDFlag(params, "", cmd); err != nil {
		return err
	}
	if err, _ := retrieveOperationEthernetSwitchPutEthernetSwitchIDRequestFlag(params, "", cmd); err != nil {
		return err
	}
	if dryRun {

		logDebugf("dry-run flag specified. Skip sending request.")
		return nil
	}
	// make request and then print result
	msgStr, err := parseOperationEthernetSwitchPutEthernetSwitchIDResult(appCli.EthernetSwitch.PutEthernetSwitchID(params))
	if err != nil {
		return err
	}
	if !debug {

		fmt.Println(msgStr)
	}
	return nil
}

// registerOperationEthernetSwitchPutEthernetSwitchIDParamFlags registers all flags needed to fill params
func registerOperationEthernetSwitchPutEthernetSwitchIDParamFlags(cmd *cobra.Command) error {
	if err := registerOperationEthernetSwitchPutEthernetSwitchIDIDParamFlags("", cmd); err != nil {
		return err
	}
	if err := registerOperationEthernetSwitchPutEthernetSwitchIDRequestParamFlags("", cmd); err != nil {
		return err
	}
	return nil
}

func registerOperationEthernetSwitchPutEthernetSwitchIDIDParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	idDescription := `Required. Ethernet switch ID`

	var idFlagName string
	if cmdPrefix == "" {
		idFlagName = "id"
	} else {
		idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
	}

	var idFlagDefault string

	_ = cmd.PersistentFlags().String(idFlagName, idFlagDefault, idDescription)

	return nil
}
func registerOperationEthernetSwitchPutEthernetSwitchIDRequestParamFlags(cmdPrefix string, cmd *cobra.Command) error {

	var requestFlagName string
	if cmdPrefix == "" {
		requestFlagName = "request"
	} else {
		requestFlagName = fmt.Sprintf("%v.request", cmdPrefix)
	}

	_ = cmd.PersistentFlags().String(requestFlagName, "", "Optional json string for [request]. Ethernet switch fields")

	// add flags for body
	if err := registerModelDtosEthernetSwitchUpdateDtoFlags(0, "dtosEthernetSwitchUpdateDto", cmd); err != nil {
		return err
	}

	return nil
}

func retrieveOperationEthernetSwitchPutEthernetSwitchIDIDFlag(m *ethernet_switch.PutEthernetSwitchIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("id") {

		var idFlagName string
		if cmdPrefix == "" {
			idFlagName = "id"
		} else {
			idFlagName = fmt.Sprintf("%v.id", cmdPrefix)
		}

		idFlagValue, err := cmd.Flags().GetString(idFlagName)
		if err != nil {
			return err, false
		}
		m.ID = idFlagValue

	}
	return nil, retAdded
}
func retrieveOperationEthernetSwitchPutEthernetSwitchIDRequestFlag(m *ethernet_switch.PutEthernetSwitchIDParams, cmdPrefix string, cmd *cobra.Command) (error, bool) {
	retAdded := false
	if cmd.Flags().Changed("request") {
		// Read request string from cmd and unmarshal
		requestValueStr, err := cmd.Flags().GetString("request")
		if err != nil {
			return err, false
		}

		requestValue := models.DtosEthernetSwitchUpdateDto{}
		if err := json.Unmarshal([]byte(requestValueStr), &requestValue); err != nil {
			return fmt.Errorf("cannot unmarshal request string in models.DtosEthernetSwitchUpdateDto: %v", err), false
		}
		m.Request = &requestValue
	}
	requestValueModel := m.Request
	if swag.IsZero(requestValueModel) {
		requestValueModel = &models.DtosEthernetSwitchUpdateDto{}
	}
	err, added := retrieveModelDtosEthernetSwitchUpdateDtoFlags(0, requestValueModel, "dtosEthernetSwitchUpdateDto", cmd)
	if err != nil {
		return err, false
	}
	if added {
		m.Request = requestValueModel
	}
	if dryRun && debug {

		requestValueDebugBytes, err := json.Marshal(m.Request)
		if err != nil {
			return err, false
		}
		logDebugf("Request dry-run payload: %v", string(requestValueDebugBytes))
	}
	retAdded = retAdded || added

	return nil, retAdded
}

// parseOperationEthernetSwitchPutEthernetSwitchIDResult parses request result and return the string content
func parseOperationEthernetSwitchPutEthernetSwitchIDResult(resp0 *ethernet_switch.PutEthernetSwitchIDOK, respErr error) (string, error) {
	if respErr != nil {

		var iResp0 interface{} = respErr
		resp0, ok := iResp0.(*ethernet_switch.PutEthernetSwitchIDOK)
		if ok {
			if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
				msgStr, err := json.Marshal(resp0.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		var iResp1 interface{} = respErr
		resp1, ok := iResp1.(*ethernet_switch.PutEthernetSwitchIDBadRequest)
		if ok {
			if !swag.IsZero(resp1) && !swag.IsZero(resp1.Payload) {
				msgStr, err := json.Marshal(resp1.Payload)
				if err != nil {
					return "", err
				}
				return string(msgStr), nil
			}
		}

		// Non schema case: warning putEthernetSwitchIdNotFound is not supported

		// Non schema case: warning putEthernetSwitchIdInternalServerError is not supported

		return "", respErr
	}

	if !swag.IsZero(resp0) && !swag.IsZero(resp0.Payload) {
		msgStr, err := json.Marshal(resp0.Payload)
		if err != nil {
			return "", err
		}
		return string(msgStr), nil
	}

	return "", nil
}
