// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteHostNetworkBridgeNameReader is a Reader for the DeleteHostNetworkBridgeName structure.
type DeleteHostNetworkBridgeNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHostNetworkBridgeNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteHostNetworkBridgeNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteHostNetworkBridgeNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteHostNetworkBridgeNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteHostNetworkBridgeNameNoContent creates a DeleteHostNetworkBridgeNameNoContent with default headers values
func NewDeleteHostNetworkBridgeNameNoContent() *DeleteHostNetworkBridgeNameNoContent {
	return &DeleteHostNetworkBridgeNameNoContent{}
}

/*
DeleteHostNetworkBridgeNameNoContent describes a response with status code 204, with default header values.

OK, but No Content
*/
type DeleteHostNetworkBridgeNameNoContent struct {
}

// IsSuccess returns true when this delete host network bridge name no content response has a 2xx status code
func (o *DeleteHostNetworkBridgeNameNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete host network bridge name no content response has a 3xx status code
func (o *DeleteHostNetworkBridgeNameNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete host network bridge name no content response has a 4xx status code
func (o *DeleteHostNetworkBridgeNameNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete host network bridge name no content response has a 5xx status code
func (o *DeleteHostNetworkBridgeNameNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete host network bridge name no content response a status code equal to that given
func (o *DeleteHostNetworkBridgeNameNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteHostNetworkBridgeNameNoContent) Error() string {
	return fmt.Sprintf("[DELETE /host/network/bridge/{name}][%d] deleteHostNetworkBridgeNameNoContent ", 204)
}

func (o *DeleteHostNetworkBridgeNameNoContent) String() string {
	return fmt.Sprintf("[DELETE /host/network/bridge/{name}][%d] deleteHostNetworkBridgeNameNoContent ", 204)
}

func (o *DeleteHostNetworkBridgeNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHostNetworkBridgeNameNotFound creates a DeleteHostNetworkBridgeNameNotFound with default headers values
func NewDeleteHostNetworkBridgeNameNotFound() *DeleteHostNetworkBridgeNameNotFound {
	return &DeleteHostNetworkBridgeNameNotFound{}
}

/*
DeleteHostNetworkBridgeNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteHostNetworkBridgeNameNotFound struct {
}

// IsSuccess returns true when this delete host network bridge name not found response has a 2xx status code
func (o *DeleteHostNetworkBridgeNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete host network bridge name not found response has a 3xx status code
func (o *DeleteHostNetworkBridgeNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete host network bridge name not found response has a 4xx status code
func (o *DeleteHostNetworkBridgeNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete host network bridge name not found response has a 5xx status code
func (o *DeleteHostNetworkBridgeNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete host network bridge name not found response a status code equal to that given
func (o *DeleteHostNetworkBridgeNameNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteHostNetworkBridgeNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /host/network/bridge/{name}][%d] deleteHostNetworkBridgeNameNotFound ", 404)
}

func (o *DeleteHostNetworkBridgeNameNotFound) String() string {
	return fmt.Sprintf("[DELETE /host/network/bridge/{name}][%d] deleteHostNetworkBridgeNameNotFound ", 404)
}

func (o *DeleteHostNetworkBridgeNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteHostNetworkBridgeNameInternalServerError creates a DeleteHostNetworkBridgeNameInternalServerError with default headers values
func NewDeleteHostNetworkBridgeNameInternalServerError() *DeleteHostNetworkBridgeNameInternalServerError {
	return &DeleteHostNetworkBridgeNameInternalServerError{}
}

/*
DeleteHostNetworkBridgeNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteHostNetworkBridgeNameInternalServerError struct {
}

// IsSuccess returns true when this delete host network bridge name internal server error response has a 2xx status code
func (o *DeleteHostNetworkBridgeNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete host network bridge name internal server error response has a 3xx status code
func (o *DeleteHostNetworkBridgeNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete host network bridge name internal server error response has a 4xx status code
func (o *DeleteHostNetworkBridgeNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete host network bridge name internal server error response has a 5xx status code
func (o *DeleteHostNetworkBridgeNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete host network bridge name internal server error response a status code equal to that given
func (o *DeleteHostNetworkBridgeNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteHostNetworkBridgeNameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /host/network/bridge/{name}][%d] deleteHostNetworkBridgeNameInternalServerError ", 500)
}

func (o *DeleteHostNetworkBridgeNameInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /host/network/bridge/{name}][%d] deleteHostNetworkBridgeNameInternalServerError ", 500)
}

func (o *DeleteHostNetworkBridgeNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
