// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetHostNetworkPingReader is a Reader for the GetHostNetworkPing structure.
type GetHostNetworkPingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHostNetworkPingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewGetHostNetworkPingNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetHostNetworkPingInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHostNetworkPingNoContent creates a GetHostNetworkPingNoContent with default headers values
func NewGetHostNetworkPingNoContent() *GetHostNetworkPingNoContent {
	return &GetHostNetworkPingNoContent{}
}

/*
GetHostNetworkPingNoContent describes a response with status code 204, with default header values.

No Content
*/
type GetHostNetworkPingNoContent struct {
}

// IsSuccess returns true when this get host network ping no content response has a 2xx status code
func (o *GetHostNetworkPingNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get host network ping no content response has a 3xx status code
func (o *GetHostNetworkPingNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get host network ping no content response has a 4xx status code
func (o *GetHostNetworkPingNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this get host network ping no content response has a 5xx status code
func (o *GetHostNetworkPingNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this get host network ping no content response a status code equal to that given
func (o *GetHostNetworkPingNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *GetHostNetworkPingNoContent) Error() string {
	return fmt.Sprintf("[GET /host/network/ping][%d] getHostNetworkPingNoContent ", 204)
}

func (o *GetHostNetworkPingNoContent) String() string {
	return fmt.Sprintf("[GET /host/network/ping][%d] getHostNetworkPingNoContent ", 204)
}

func (o *GetHostNetworkPingNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHostNetworkPingInternalServerError creates a GetHostNetworkPingInternalServerError with default headers values
func NewGetHostNetworkPingInternalServerError() *GetHostNetworkPingInternalServerError {
	return &GetHostNetworkPingInternalServerError{}
}

/*
GetHostNetworkPingInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetHostNetworkPingInternalServerError struct {
}

// IsSuccess returns true when this get host network ping internal server error response has a 2xx status code
func (o *GetHostNetworkPingInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get host network ping internal server error response has a 3xx status code
func (o *GetHostNetworkPingInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get host network ping internal server error response has a 4xx status code
func (o *GetHostNetworkPingInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get host network ping internal server error response has a 5xx status code
func (o *GetHostNetworkPingInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get host network ping internal server error response a status code equal to that given
func (o *GetHostNetworkPingInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetHostNetworkPingInternalServerError) Error() string {
	return fmt.Sprintf("[GET /host/network/ping][%d] getHostNetworkPingInternalServerError ", 500)
}

func (o *GetHostNetworkPingInternalServerError) String() string {
	return fmt.Sprintf("[GET /host/network/ping][%d] getHostNetworkPingInternalServerError ", 500)
}

func (o *GetHostNetworkPingInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
