// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// GetHostNetworkVlanNameReader is a Reader for the GetHostNetworkVlanName structure.
type GetHostNetworkVlanNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetHostNetworkVlanNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetHostNetworkVlanNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetHostNetworkVlanNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetHostNetworkVlanNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetHostNetworkVlanNameOK creates a GetHostNetworkVlanNameOK with default headers values
func NewGetHostNetworkVlanNameOK() *GetHostNetworkVlanNameOK {
	return &GetHostNetworkVlanNameOK{}
}

/*
GetHostNetworkVlanNameOK describes a response with status code 200, with default header values.

OK
*/
type GetHostNetworkVlanNameOK struct {
	Payload *models.DtosHostNetworkVlanDto
}

// IsSuccess returns true when this get host network vlan name o k response has a 2xx status code
func (o *GetHostNetworkVlanNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get host network vlan name o k response has a 3xx status code
func (o *GetHostNetworkVlanNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get host network vlan name o k response has a 4xx status code
func (o *GetHostNetworkVlanNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get host network vlan name o k response has a 5xx status code
func (o *GetHostNetworkVlanNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get host network vlan name o k response a status code equal to that given
func (o *GetHostNetworkVlanNameOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetHostNetworkVlanNameOK) Error() string {
	return fmt.Sprintf("[GET /host/network/vlan/{name}][%d] getHostNetworkVlanNameOK  %+v", 200, o.Payload)
}

func (o *GetHostNetworkVlanNameOK) String() string {
	return fmt.Sprintf("[GET /host/network/vlan/{name}][%d] getHostNetworkVlanNameOK  %+v", 200, o.Payload)
}

func (o *GetHostNetworkVlanNameOK) GetPayload() *models.DtosHostNetworkVlanDto {
	return o.Payload
}

func (o *GetHostNetworkVlanNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosHostNetworkVlanDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHostNetworkVlanNameNotFound creates a GetHostNetworkVlanNameNotFound with default headers values
func NewGetHostNetworkVlanNameNotFound() *GetHostNetworkVlanNameNotFound {
	return &GetHostNetworkVlanNameNotFound{}
}

/*
GetHostNetworkVlanNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetHostNetworkVlanNameNotFound struct {
}

// IsSuccess returns true when this get host network vlan name not found response has a 2xx status code
func (o *GetHostNetworkVlanNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get host network vlan name not found response has a 3xx status code
func (o *GetHostNetworkVlanNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get host network vlan name not found response has a 4xx status code
func (o *GetHostNetworkVlanNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get host network vlan name not found response has a 5xx status code
func (o *GetHostNetworkVlanNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get host network vlan name not found response a status code equal to that given
func (o *GetHostNetworkVlanNameNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetHostNetworkVlanNameNotFound) Error() string {
	return fmt.Sprintf("[GET /host/network/vlan/{name}][%d] getHostNetworkVlanNameNotFound ", 404)
}

func (o *GetHostNetworkVlanNameNotFound) String() string {
	return fmt.Sprintf("[GET /host/network/vlan/{name}][%d] getHostNetworkVlanNameNotFound ", 404)
}

func (o *GetHostNetworkVlanNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetHostNetworkVlanNameInternalServerError creates a GetHostNetworkVlanNameInternalServerError with default headers values
func NewGetHostNetworkVlanNameInternalServerError() *GetHostNetworkVlanNameInternalServerError {
	return &GetHostNetworkVlanNameInternalServerError{}
}

/*
GetHostNetworkVlanNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetHostNetworkVlanNameInternalServerError struct {
}

// IsSuccess returns true when this get host network vlan name internal server error response has a 2xx status code
func (o *GetHostNetworkVlanNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get host network vlan name internal server error response has a 3xx status code
func (o *GetHostNetworkVlanNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get host network vlan name internal server error response has a 4xx status code
func (o *GetHostNetworkVlanNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get host network vlan name internal server error response has a 5xx status code
func (o *GetHostNetworkVlanNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get host network vlan name internal server error response a status code equal to that given
func (o *GetHostNetworkVlanNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetHostNetworkVlanNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /host/network/vlan/{name}][%d] getHostNetworkVlanNameInternalServerError ", 500)
}

func (o *GetHostNetworkVlanNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /host/network/vlan/{name}][%d] getHostNetworkVlanNameInternalServerError ", 500)
}

func (o *GetHostNetworkVlanNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
