// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHostNetworkVlanNameParams creates a new GetHostNetworkVlanNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHostNetworkVlanNameParams() *GetHostNetworkVlanNameParams {
	return &GetHostNetworkVlanNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHostNetworkVlanNameParamsWithTimeout creates a new GetHostNetworkVlanNameParams object
// with the ability to set a timeout on a request.
func NewGetHostNetworkVlanNameParamsWithTimeout(timeout time.Duration) *GetHostNetworkVlanNameParams {
	return &GetHostNetworkVlanNameParams{
		timeout: timeout,
	}
}

// NewGetHostNetworkVlanNameParamsWithContext creates a new GetHostNetworkVlanNameParams object
// with the ability to set a context for a request.
func NewGetHostNetworkVlanNameParamsWithContext(ctx context.Context) *GetHostNetworkVlanNameParams {
	return &GetHostNetworkVlanNameParams{
		Context: ctx,
	}
}

// NewGetHostNetworkVlanNameParamsWithHTTPClient creates a new GetHostNetworkVlanNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHostNetworkVlanNameParamsWithHTTPClient(client *http.Client) *GetHostNetworkVlanNameParams {
	return &GetHostNetworkVlanNameParams{
		HTTPClient: client,
	}
}

/*
GetHostNetworkVlanNameParams contains all the parameters to send to the API endpoint

	for the get host network vlan name operation.

	Typically these are written to a http.Request.
*/
type GetHostNetworkVlanNameParams struct {

	/* Name.

	   Vlan name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get host network vlan name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHostNetworkVlanNameParams) WithDefaults() *GetHostNetworkVlanNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get host network vlan name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHostNetworkVlanNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) WithTimeout(timeout time.Duration) *GetHostNetworkVlanNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) WithContext(ctx context.Context) *GetHostNetworkVlanNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) WithHTTPClient(client *http.Client) *GetHostNetworkVlanNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) WithName(name string) *GetHostNetworkVlanNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get host network vlan name params
func (o *GetHostNetworkVlanNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetHostNetworkVlanNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
