// Code generated by go-swagger; DO NOT EDIT.

package host

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHostNetworkPingParams creates a new GetHostNetworkPingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetHostNetworkPingParams() *GetHostNetworkPingParams {
	return &GetHostNetworkPingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetHostNetworkPingParamsWithTimeout creates a new GetHostNetworkPingParams object
// with the ability to set a timeout on a request.
func NewGetHostNetworkPingParamsWithTimeout(timeout time.Duration) *GetHostNetworkPingParams {
	return &GetHostNetworkPingParams{
		timeout: timeout,
	}
}

// NewGetHostNetworkPingParamsWithContext creates a new GetHostNetworkPingParams object
// with the ability to set a context for a request.
func NewGetHostNetworkPingParamsWithContext(ctx context.Context) *GetHostNetworkPingParams {
	return &GetHostNetworkPingParams{
		Context: ctx,
	}
}

// NewGetHostNetworkPingParamsWithHTTPClient creates a new GetHostNetworkPingParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetHostNetworkPingParamsWithHTTPClient(client *http.Client) *GetHostNetworkPingParams {
	return &GetHostNetworkPingParams{
		HTTPClient: client,
	}
}

/*
GetHostNetworkPingParams contains all the parameters to send to the API endpoint

	for the get host network ping operation.

	Typically these are written to a http.Request.
*/
type GetHostNetworkPingParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get host network ping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHostNetworkPingParams) WithDefaults() *GetHostNetworkPingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get host network ping params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetHostNetworkPingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get host network ping params
func (o *GetHostNetworkPingParams) WithTimeout(timeout time.Duration) *GetHostNetworkPingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get host network ping params
func (o *GetHostNetworkPingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get host network ping params
func (o *GetHostNetworkPingParams) WithContext(ctx context.Context) *GetHostNetworkPingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get host network ping params
func (o *GetHostNetworkPingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get host network ping params
func (o *GetHostNetworkPingParams) WithHTTPClient(client *http.Client) *GetHostNetworkPingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get host network ping params
func (o *GetHostNetworkPingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetHostNetworkPingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
