// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteEthernetSwitchIDParams creates a new DeleteEthernetSwitchIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteEthernetSwitchIDParams() *DeleteEthernetSwitchIDParams {
	return &DeleteEthernetSwitchIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEthernetSwitchIDParamsWithTimeout creates a new DeleteEthernetSwitchIDParams object
// with the ability to set a timeout on a request.
func NewDeleteEthernetSwitchIDParamsWithTimeout(timeout time.Duration) *DeleteEthernetSwitchIDParams {
	return &DeleteEthernetSwitchIDParams{
		timeout: timeout,
	}
}

// NewDeleteEthernetSwitchIDParamsWithContext creates a new DeleteEthernetSwitchIDParams object
// with the ability to set a context for a request.
func NewDeleteEthernetSwitchIDParamsWithContext(ctx context.Context) *DeleteEthernetSwitchIDParams {
	return &DeleteEthernetSwitchIDParams{
		Context: ctx,
	}
}

// NewDeleteEthernetSwitchIDParamsWithHTTPClient creates a new DeleteEthernetSwitchIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteEthernetSwitchIDParamsWithHTTPClient(client *http.Client) *DeleteEthernetSwitchIDParams {
	return &DeleteEthernetSwitchIDParams{
		HTTPClient: client,
	}
}

/*
DeleteEthernetSwitchIDParams contains all the parameters to send to the API endpoint

	for the delete ethernet switch ID operation.

	Typically these are written to a http.Request.
*/
type DeleteEthernetSwitchIDParams struct {

	/* ID.

	   Ethernet switch ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete ethernet switch ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEthernetSwitchIDParams) WithDefaults() *DeleteEthernetSwitchIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete ethernet switch ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteEthernetSwitchIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) WithTimeout(timeout time.Duration) *DeleteEthernetSwitchIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) WithContext(ctx context.Context) *DeleteEthernetSwitchIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) WithHTTPClient(client *http.Client) *DeleteEthernetSwitchIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) WithID(id string) *DeleteEthernetSwitchIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete ethernet switch ID params
func (o *DeleteEthernetSwitchIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEthernetSwitchIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
