// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteEthernetSwitchIDPortPortIDReader is a Reader for the DeleteEthernetSwitchIDPortPortID structure.
type DeleteEthernetSwitchIDPortPortIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteEthernetSwitchIDPortPortIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteEthernetSwitchIDPortPortIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteEthernetSwitchIDPortPortIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteEthernetSwitchIDPortPortIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteEthernetSwitchIDPortPortIDNoContent creates a DeleteEthernetSwitchIDPortPortIDNoContent with default headers values
func NewDeleteEthernetSwitchIDPortPortIDNoContent() *DeleteEthernetSwitchIDPortPortIDNoContent {
	return &DeleteEthernetSwitchIDPortPortIDNoContent{}
}

/*
DeleteEthernetSwitchIDPortPortIDNoContent describes a response with status code 204, with default header values.

OK, but No Content
*/
type DeleteEthernetSwitchIDPortPortIDNoContent struct {
}

// IsSuccess returns true when this delete ethernet switch Id port port Id no content response has a 2xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete ethernet switch Id port port Id no content response has a 3xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete ethernet switch Id port port Id no content response has a 4xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete ethernet switch Id port port Id no content response has a 5xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete ethernet switch Id port port Id no content response a status code equal to that given
func (o *DeleteEthernetSwitchIDPortPortIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteEthernetSwitchIDPortPortIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /ethernet-switch/{id}/port/{portID}][%d] deleteEthernetSwitchIdPortPortIdNoContent ", 204)
}

func (o *DeleteEthernetSwitchIDPortPortIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /ethernet-switch/{id}/port/{portID}][%d] deleteEthernetSwitchIdPortPortIdNoContent ", 204)
}

func (o *DeleteEthernetSwitchIDPortPortIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEthernetSwitchIDPortPortIDNotFound creates a DeleteEthernetSwitchIDPortPortIDNotFound with default headers values
func NewDeleteEthernetSwitchIDPortPortIDNotFound() *DeleteEthernetSwitchIDPortPortIDNotFound {
	return &DeleteEthernetSwitchIDPortPortIDNotFound{}
}

/*
DeleteEthernetSwitchIDPortPortIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteEthernetSwitchIDPortPortIDNotFound struct {
}

// IsSuccess returns true when this delete ethernet switch Id port port Id not found response has a 2xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete ethernet switch Id port port Id not found response has a 3xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete ethernet switch Id port port Id not found response has a 4xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete ethernet switch Id port port Id not found response has a 5xx status code
func (o *DeleteEthernetSwitchIDPortPortIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete ethernet switch Id port port Id not found response a status code equal to that given
func (o *DeleteEthernetSwitchIDPortPortIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteEthernetSwitchIDPortPortIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /ethernet-switch/{id}/port/{portID}][%d] deleteEthernetSwitchIdPortPortIdNotFound ", 404)
}

func (o *DeleteEthernetSwitchIDPortPortIDNotFound) String() string {
	return fmt.Sprintf("[DELETE /ethernet-switch/{id}/port/{portID}][%d] deleteEthernetSwitchIdPortPortIdNotFound ", 404)
}

func (o *DeleteEthernetSwitchIDPortPortIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteEthernetSwitchIDPortPortIDInternalServerError creates a DeleteEthernetSwitchIDPortPortIDInternalServerError with default headers values
func NewDeleteEthernetSwitchIDPortPortIDInternalServerError() *DeleteEthernetSwitchIDPortPortIDInternalServerError {
	return &DeleteEthernetSwitchIDPortPortIDInternalServerError{}
}

/*
DeleteEthernetSwitchIDPortPortIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteEthernetSwitchIDPortPortIDInternalServerError struct {
}

// IsSuccess returns true when this delete ethernet switch Id port port Id internal server error response has a 2xx status code
func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete ethernet switch Id port port Id internal server error response has a 3xx status code
func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete ethernet switch Id port port Id internal server error response has a 4xx status code
func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete ethernet switch Id port port Id internal server error response has a 5xx status code
func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete ethernet switch Id port port Id internal server error response a status code equal to that given
func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /ethernet-switch/{id}/port/{portID}][%d] deleteEthernetSwitchIdPortPortIdInternalServerError ", 500)
}

func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /ethernet-switch/{id}/port/{portID}][%d] deleteEthernetSwitchIdPortPortIdInternalServerError ", 500)
}

func (o *DeleteEthernetSwitchIDPortPortIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
