// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// GetEthernetSwitchIDPortPortIDReader is a Reader for the GetEthernetSwitchIDPortPortID structure.
type GetEthernetSwitchIDPortPortIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEthernetSwitchIDPortPortIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEthernetSwitchIDPortPortIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewGetEthernetSwitchIDPortPortIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetEthernetSwitchIDPortPortIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEthernetSwitchIDPortPortIDOK creates a GetEthernetSwitchIDPortPortIDOK with default headers values
func NewGetEthernetSwitchIDPortPortIDOK() *GetEthernetSwitchIDPortPortIDOK {
	return &GetEthernetSwitchIDPortPortIDOK{}
}

/*
GetEthernetSwitchIDPortPortIDOK describes a response with status code 200, with default header values.

OK
*/
type GetEthernetSwitchIDPortPortIDOK struct {
	Payload *models.DtosEthernetSwitchPortDto
}

// IsSuccess returns true when this get ethernet switch Id port port Id o k response has a 2xx status code
func (o *GetEthernetSwitchIDPortPortIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ethernet switch Id port port Id o k response has a 3xx status code
func (o *GetEthernetSwitchIDPortPortIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ethernet switch Id port port Id o k response has a 4xx status code
func (o *GetEthernetSwitchIDPortPortIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ethernet switch Id port port Id o k response has a 5xx status code
func (o *GetEthernetSwitchIDPortPortIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ethernet switch Id port port Id o k response a status code equal to that given
func (o *GetEthernetSwitchIDPortPortIDOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetEthernetSwitchIDPortPortIDOK) Error() string {
	return fmt.Sprintf("[GET /ethernet-switch/{id}/port/{portID}][%d] getEthernetSwitchIdPortPortIdOK  %+v", 200, o.Payload)
}

func (o *GetEthernetSwitchIDPortPortIDOK) String() string {
	return fmt.Sprintf("[GET /ethernet-switch/{id}/port/{portID}][%d] getEthernetSwitchIdPortPortIdOK  %+v", 200, o.Payload)
}

func (o *GetEthernetSwitchIDPortPortIDOK) GetPayload() *models.DtosEthernetSwitchPortDto {
	return o.Payload
}

func (o *GetEthernetSwitchIDPortPortIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosEthernetSwitchPortDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEthernetSwitchIDPortPortIDNotFound creates a GetEthernetSwitchIDPortPortIDNotFound with default headers values
func NewGetEthernetSwitchIDPortPortIDNotFound() *GetEthernetSwitchIDPortPortIDNotFound {
	return &GetEthernetSwitchIDPortPortIDNotFound{}
}

/*
GetEthernetSwitchIDPortPortIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetEthernetSwitchIDPortPortIDNotFound struct {
}

// IsSuccess returns true when this get ethernet switch Id port port Id not found response has a 2xx status code
func (o *GetEthernetSwitchIDPortPortIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get ethernet switch Id port port Id not found response has a 3xx status code
func (o *GetEthernetSwitchIDPortPortIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ethernet switch Id port port Id not found response has a 4xx status code
func (o *GetEthernetSwitchIDPortPortIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get ethernet switch Id port port Id not found response has a 5xx status code
func (o *GetEthernetSwitchIDPortPortIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get ethernet switch Id port port Id not found response a status code equal to that given
func (o *GetEthernetSwitchIDPortPortIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetEthernetSwitchIDPortPortIDNotFound) Error() string {
	return fmt.Sprintf("[GET /ethernet-switch/{id}/port/{portID}][%d] getEthernetSwitchIdPortPortIdNotFound ", 404)
}

func (o *GetEthernetSwitchIDPortPortIDNotFound) String() string {
	return fmt.Sprintf("[GET /ethernet-switch/{id}/port/{portID}][%d] getEthernetSwitchIdPortPortIdNotFound ", 404)
}

func (o *GetEthernetSwitchIDPortPortIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetEthernetSwitchIDPortPortIDInternalServerError creates a GetEthernetSwitchIDPortPortIDInternalServerError with default headers values
func NewGetEthernetSwitchIDPortPortIDInternalServerError() *GetEthernetSwitchIDPortPortIDInternalServerError {
	return &GetEthernetSwitchIDPortPortIDInternalServerError{}
}

/*
GetEthernetSwitchIDPortPortIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetEthernetSwitchIDPortPortIDInternalServerError struct {
}

// IsSuccess returns true when this get ethernet switch Id port port Id internal server error response has a 2xx status code
func (o *GetEthernetSwitchIDPortPortIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get ethernet switch Id port port Id internal server error response has a 3xx status code
func (o *GetEthernetSwitchIDPortPortIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ethernet switch Id port port Id internal server error response has a 4xx status code
func (o *GetEthernetSwitchIDPortPortIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ethernet switch Id port port Id internal server error response has a 5xx status code
func (o *GetEthernetSwitchIDPortPortIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get ethernet switch Id port port Id internal server error response a status code equal to that given
func (o *GetEthernetSwitchIDPortPortIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetEthernetSwitchIDPortPortIDInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ethernet-switch/{id}/port/{portID}][%d] getEthernetSwitchIdPortPortIdInternalServerError ", 500)
}

func (o *GetEthernetSwitchIDPortPortIDInternalServerError) String() string {
	return fmt.Sprintf("[GET /ethernet-switch/{id}/port/{portID}][%d] getEthernetSwitchIdPortPortIdInternalServerError ", 500)
}

func (o *GetEthernetSwitchIDPortPortIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
