// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// GetEthernetSwitchReader is a Reader for the GetEthernetSwitch structure.
type GetEthernetSwitchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetEthernetSwitchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetEthernetSwitchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetEthernetSwitchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetEthernetSwitchOK creates a GetEthernetSwitchOK with default headers values
func NewGetEthernetSwitchOK() *GetEthernetSwitchOK {
	return &GetEthernetSwitchOK{}
}

/*
GetEthernetSwitchOK describes a response with status code 200, with default header values.

OK
*/
type GetEthernetSwitchOK struct {
	Payload *models.DtosPaginatedItemsDtoDtosEthernetSwitchDto
}

// IsSuccess returns true when this get ethernet switch o k response has a 2xx status code
func (o *GetEthernetSwitchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get ethernet switch o k response has a 3xx status code
func (o *GetEthernetSwitchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ethernet switch o k response has a 4xx status code
func (o *GetEthernetSwitchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ethernet switch o k response has a 5xx status code
func (o *GetEthernetSwitchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get ethernet switch o k response a status code equal to that given
func (o *GetEthernetSwitchOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetEthernetSwitchOK) Error() string {
	return fmt.Sprintf("[GET /ethernet-switch/][%d] getEthernetSwitchOK  %+v", 200, o.Payload)
}

func (o *GetEthernetSwitchOK) String() string {
	return fmt.Sprintf("[GET /ethernet-switch/][%d] getEthernetSwitchOK  %+v", 200, o.Payload)
}

func (o *GetEthernetSwitchOK) GetPayload() *models.DtosPaginatedItemsDtoDtosEthernetSwitchDto {
	return o.Payload
}

func (o *GetEthernetSwitchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosPaginatedItemsDtoDtosEthernetSwitchDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetEthernetSwitchInternalServerError creates a GetEthernetSwitchInternalServerError with default headers values
func NewGetEthernetSwitchInternalServerError() *GetEthernetSwitchInternalServerError {
	return &GetEthernetSwitchInternalServerError{}
}

/*
GetEthernetSwitchInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetEthernetSwitchInternalServerError struct {
}

// IsSuccess returns true when this get ethernet switch internal server error response has a 2xx status code
func (o *GetEthernetSwitchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get ethernet switch internal server error response has a 3xx status code
func (o *GetEthernetSwitchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get ethernet switch internal server error response has a 4xx status code
func (o *GetEthernetSwitchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get ethernet switch internal server error response has a 5xx status code
func (o *GetEthernetSwitchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get ethernet switch internal server error response a status code equal to that given
func (o *GetEthernetSwitchInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetEthernetSwitchInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ethernet-switch/][%d] getEthernetSwitchInternalServerError ", 500)
}

func (o *GetEthernetSwitchInternalServerError) String() string {
	return fmt.Sprintf("[GET /ethernet-switch/][%d] getEthernetSwitchInternalServerError ", 500)
}

func (o *GetEthernetSwitchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
