// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetEthernetSwitchIDPortParams creates a new GetEthernetSwitchIDPortParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetEthernetSwitchIDPortParams() *GetEthernetSwitchIDPortParams {
	return &GetEthernetSwitchIDPortParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetEthernetSwitchIDPortParamsWithTimeout creates a new GetEthernetSwitchIDPortParams object
// with the ability to set a timeout on a request.
func NewGetEthernetSwitchIDPortParamsWithTimeout(timeout time.Duration) *GetEthernetSwitchIDPortParams {
	return &GetEthernetSwitchIDPortParams{
		timeout: timeout,
	}
}

// NewGetEthernetSwitchIDPortParamsWithContext creates a new GetEthernetSwitchIDPortParams object
// with the ability to set a context for a request.
func NewGetEthernetSwitchIDPortParamsWithContext(ctx context.Context) *GetEthernetSwitchIDPortParams {
	return &GetEthernetSwitchIDPortParams{
		Context: ctx,
	}
}

// NewGetEthernetSwitchIDPortParamsWithHTTPClient creates a new GetEthernetSwitchIDPortParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetEthernetSwitchIDPortParamsWithHTTPClient(client *http.Client) *GetEthernetSwitchIDPortParams {
	return &GetEthernetSwitchIDPortParams{
		HTTPClient: client,
	}
}

/*
GetEthernetSwitchIDPortParams contains all the parameters to send to the API endpoint

	for the get ethernet switch ID port operation.

	Typically these are written to a http.Request.
*/
type GetEthernetSwitchIDPortParams struct {

	/* ID.

	   Ethernet switch ID
	*/
	ID string

	/* OrderBy.

	   Order by field, default - Name
	*/
	OrderBy *string

	/* OrderDirection.

	   'asc' or 'desc' for ascending or descending order, default - asc
	*/
	OrderDirection *string

	/* Page.

	   Page number, default - 1
	*/
	Page *int64

	/* PageSize.

	   Number of entities per page, default - 10
	*/
	PageSize *int64

	/* Search.

	   Searchable value in entity, default -
	*/
	Search *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ethernet switch ID port params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEthernetSwitchIDPortParams) WithDefaults() *GetEthernetSwitchIDPortParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ethernet switch ID port params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetEthernetSwitchIDPortParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithTimeout(timeout time.Duration) *GetEthernetSwitchIDPortParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithContext(ctx context.Context) *GetEthernetSwitchIDPortParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithHTTPClient(client *http.Client) *GetEthernetSwitchIDPortParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithID(id string) *GetEthernetSwitchIDPortParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetID(id string) {
	o.ID = id
}

// WithOrderBy adds the orderBy to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithOrderBy(orderBy *string) *GetEthernetSwitchIDPortParams {
	o.SetOrderBy(orderBy)
	return o
}

// SetOrderBy adds the orderBy to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetOrderBy(orderBy *string) {
	o.OrderBy = orderBy
}

// WithOrderDirection adds the orderDirection to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithOrderDirection(orderDirection *string) *GetEthernetSwitchIDPortParams {
	o.SetOrderDirection(orderDirection)
	return o
}

// SetOrderDirection adds the orderDirection to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetOrderDirection(orderDirection *string) {
	o.OrderDirection = orderDirection
}

// WithPage adds the page to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithPage(page *int64) *GetEthernetSwitchIDPortParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetPage(page *int64) {
	o.Page = page
}

// WithPageSize adds the pageSize to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithPageSize(pageSize *int64) *GetEthernetSwitchIDPortParams {
	o.SetPageSize(pageSize)
	return o
}

// SetPageSize adds the pageSize to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetPageSize(pageSize *int64) {
	o.PageSize = pageSize
}

// WithSearch adds the search to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) WithSearch(search *string) *GetEthernetSwitchIDPortParams {
	o.SetSearch(search)
	return o
}

// SetSearch adds the search to the get ethernet switch ID port params
func (o *GetEthernetSwitchIDPortParams) SetSearch(search *string) {
	o.Search = search
}

// WriteToRequest writes these params to a swagger request
func (o *GetEthernetSwitchIDPortParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.OrderBy != nil {

		// query param orderBy
		var qrOrderBy string

		if o.OrderBy != nil {
			qrOrderBy = *o.OrderBy
		}
		qOrderBy := qrOrderBy
		if qOrderBy != "" {

			if err := r.SetQueryParam("orderBy", qOrderBy); err != nil {
				return err
			}
		}
	}

	if o.OrderDirection != nil {

		// query param orderDirection
		var qrOrderDirection string

		if o.OrderDirection != nil {
			qrOrderDirection = *o.OrderDirection
		}
		qOrderDirection := qrOrderDirection
		if qOrderDirection != "" {

			if err := r.SetQueryParam("orderDirection", qOrderDirection); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.PageSize != nil {

		// query param pageSize
		var qrPageSize int64

		if o.PageSize != nil {
			qrPageSize = *o.PageSize
		}
		qPageSize := swag.FormatInt64(qrPageSize)
		if qPageSize != "" {

			if err := r.SetQueryParam("pageSize", qPageSize); err != nil {
				return err
			}
		}
	}

	if o.Search != nil {

		// query param search
		var qrSearch string

		if o.Search != nil {
			qrSearch = *o.Search
		}
		qSearch := qrSearch
		if qSearch != "" {

			if err := r.SetQueryParam("search", qSearch); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
