// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// NewPostEthernetSwitchIDVlanParams creates a new PostEthernetSwitchIDVlanParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostEthernetSwitchIDVlanParams() *PostEthernetSwitchIDVlanParams {
	return &PostEthernetSwitchIDVlanParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostEthernetSwitchIDVlanParamsWithTimeout creates a new PostEthernetSwitchIDVlanParams object
// with the ability to set a timeout on a request.
func NewPostEthernetSwitchIDVlanParamsWithTimeout(timeout time.Duration) *PostEthernetSwitchIDVlanParams {
	return &PostEthernetSwitchIDVlanParams{
		timeout: timeout,
	}
}

// NewPostEthernetSwitchIDVlanParamsWithContext creates a new PostEthernetSwitchIDVlanParams object
// with the ability to set a context for a request.
func NewPostEthernetSwitchIDVlanParamsWithContext(ctx context.Context) *PostEthernetSwitchIDVlanParams {
	return &PostEthernetSwitchIDVlanParams{
		Context: ctx,
	}
}

// NewPostEthernetSwitchIDVlanParamsWithHTTPClient creates a new PostEthernetSwitchIDVlanParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostEthernetSwitchIDVlanParamsWithHTTPClient(client *http.Client) *PostEthernetSwitchIDVlanParams {
	return &PostEthernetSwitchIDVlanParams{
		HTTPClient: client,
	}
}

/*
PostEthernetSwitchIDVlanParams contains all the parameters to send to the API endpoint

	for the post ethernet switch ID vlan operation.

	Typically these are written to a http.Request.
*/
type PostEthernetSwitchIDVlanParams struct {

	/* ID.

	   Ethernet switch ID
	*/
	ID string

	/* Request.

	   Ethernet switch VLAN fields
	*/
	Request *models.DtosEthernetSwitchVLANCreateDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post ethernet switch ID vlan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEthernetSwitchIDVlanParams) WithDefaults() *PostEthernetSwitchIDVlanParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post ethernet switch ID vlan params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEthernetSwitchIDVlanParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) WithTimeout(timeout time.Duration) *PostEthernetSwitchIDVlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) WithContext(ctx context.Context) *PostEthernetSwitchIDVlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) WithHTTPClient(client *http.Client) *PostEthernetSwitchIDVlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) WithID(id string) *PostEthernetSwitchIDVlanParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) SetID(id string) {
	o.ID = id
}

// WithRequest adds the request to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) WithRequest(request *models.DtosEthernetSwitchVLANCreateDto) *PostEthernetSwitchIDVlanParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post ethernet switch ID vlan params
func (o *PostEthernetSwitchIDVlanParams) SetRequest(request *models.DtosEthernetSwitchVLANCreateDto) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostEthernetSwitchIDVlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
