// Code generated by go-swagger; DO NOT EDIT.

package ethernet_switch

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// NewPostEthernetSwitchParams creates a new PostEthernetSwitchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostEthernetSwitchParams() *PostEthernetSwitchParams {
	return &PostEthernetSwitchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostEthernetSwitchParamsWithTimeout creates a new PostEthernetSwitchParams object
// with the ability to set a timeout on a request.
func NewPostEthernetSwitchParamsWithTimeout(timeout time.Duration) *PostEthernetSwitchParams {
	return &PostEthernetSwitchParams{
		timeout: timeout,
	}
}

// NewPostEthernetSwitchParamsWithContext creates a new PostEthernetSwitchParams object
// with the ability to set a context for a request.
func NewPostEthernetSwitchParamsWithContext(ctx context.Context) *PostEthernetSwitchParams {
	return &PostEthernetSwitchParams{
		Context: ctx,
	}
}

// NewPostEthernetSwitchParamsWithHTTPClient creates a new PostEthernetSwitchParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostEthernetSwitchParamsWithHTTPClient(client *http.Client) *PostEthernetSwitchParams {
	return &PostEthernetSwitchParams{
		HTTPClient: client,
	}
}

/*
PostEthernetSwitchParams contains all the parameters to send to the API endpoint

	for the post ethernet switch operation.

	Typically these are written to a http.Request.
*/
type PostEthernetSwitchParams struct {

	/* Request.

	   Ethernet switch fields
	*/
	Request *models.DtosEthernetSwitchCreateDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post ethernet switch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEthernetSwitchParams) WithDefaults() *PostEthernetSwitchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post ethernet switch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostEthernetSwitchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post ethernet switch params
func (o *PostEthernetSwitchParams) WithTimeout(timeout time.Duration) *PostEthernetSwitchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post ethernet switch params
func (o *PostEthernetSwitchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post ethernet switch params
func (o *PostEthernetSwitchParams) WithContext(ctx context.Context) *PostEthernetSwitchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post ethernet switch params
func (o *PostEthernetSwitchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post ethernet switch params
func (o *PostEthernetSwitchParams) WithHTTPClient(client *http.Client) *PostEthernetSwitchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post ethernet switch params
func (o *PostEthernetSwitchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post ethernet switch params
func (o *PostEthernetSwitchParams) WithRequest(request *models.DtosEthernetSwitchCreateDto) *PostEthernetSwitchParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post ethernet switch params
func (o *PostEthernetSwitchParams) SetRequest(request *models.DtosEthernetSwitchCreateDto) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostEthernetSwitchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
