// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDhcpIDLeaseLeaseIDReader is a Reader for the DeleteDhcpIDLeaseLeaseID structure.
type DeleteDhcpIDLeaseLeaseIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDhcpIDLeaseLeaseIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteDhcpIDLeaseLeaseIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteDhcpIDLeaseLeaseIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteDhcpIDLeaseLeaseIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDhcpIDLeaseLeaseIDNoContent creates a DeleteDhcpIDLeaseLeaseIDNoContent with default headers values
func NewDeleteDhcpIDLeaseLeaseIDNoContent() *DeleteDhcpIDLeaseLeaseIDNoContent {
	return &DeleteDhcpIDLeaseLeaseIDNoContent{}
}

/*
DeleteDhcpIDLeaseLeaseIDNoContent describes a response with status code 204, with default header values.

OK, but No Content
*/
type DeleteDhcpIDLeaseLeaseIDNoContent struct {
}

// IsSuccess returns true when this delete dhcp Id lease lease Id no content response has a 2xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete dhcp Id lease lease Id no content response has a 3xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete dhcp Id lease lease Id no content response has a 4xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete dhcp Id lease lease Id no content response has a 5xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete dhcp Id lease lease Id no content response a status code equal to that given
func (o *DeleteDhcpIDLeaseLeaseIDNoContent) IsCode(code int) bool {
	return code == 204
}

func (o *DeleteDhcpIDLeaseLeaseIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /dhcp/{id}/lease/{leaseID}][%d] deleteDhcpIdLeaseLeaseIdNoContent ", 204)
}

func (o *DeleteDhcpIDLeaseLeaseIDNoContent) String() string {
	return fmt.Sprintf("[DELETE /dhcp/{id}/lease/{leaseID}][%d] deleteDhcpIdLeaseLeaseIdNoContent ", 204)
}

func (o *DeleteDhcpIDLeaseLeaseIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDhcpIDLeaseLeaseIDNotFound creates a DeleteDhcpIDLeaseLeaseIDNotFound with default headers values
func NewDeleteDhcpIDLeaseLeaseIDNotFound() *DeleteDhcpIDLeaseLeaseIDNotFound {
	return &DeleteDhcpIDLeaseLeaseIDNotFound{}
}

/*
DeleteDhcpIDLeaseLeaseIDNotFound describes a response with status code 404, with default header values.

Not Found
*/
type DeleteDhcpIDLeaseLeaseIDNotFound struct {
}

// IsSuccess returns true when this delete dhcp Id lease lease Id not found response has a 2xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete dhcp Id lease lease Id not found response has a 3xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete dhcp Id lease lease Id not found response has a 4xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete dhcp Id lease lease Id not found response has a 5xx status code
func (o *DeleteDhcpIDLeaseLeaseIDNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete dhcp Id lease lease Id not found response a status code equal to that given
func (o *DeleteDhcpIDLeaseLeaseIDNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *DeleteDhcpIDLeaseLeaseIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /dhcp/{id}/lease/{leaseID}][%d] deleteDhcpIdLeaseLeaseIdNotFound ", 404)
}

func (o *DeleteDhcpIDLeaseLeaseIDNotFound) String() string {
	return fmt.Sprintf("[DELETE /dhcp/{id}/lease/{leaseID}][%d] deleteDhcpIdLeaseLeaseIdNotFound ", 404)
}

func (o *DeleteDhcpIDLeaseLeaseIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDhcpIDLeaseLeaseIDInternalServerError creates a DeleteDhcpIDLeaseLeaseIDInternalServerError with default headers values
func NewDeleteDhcpIDLeaseLeaseIDInternalServerError() *DeleteDhcpIDLeaseLeaseIDInternalServerError {
	return &DeleteDhcpIDLeaseLeaseIDInternalServerError{}
}

/*
DeleteDhcpIDLeaseLeaseIDInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type DeleteDhcpIDLeaseLeaseIDInternalServerError struct {
}

// IsSuccess returns true when this delete dhcp Id lease lease Id internal server error response has a 2xx status code
func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete dhcp Id lease lease Id internal server error response has a 3xx status code
func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete dhcp Id lease lease Id internal server error response has a 4xx status code
func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete dhcp Id lease lease Id internal server error response has a 5xx status code
func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete dhcp Id lease lease Id internal server error response a status code equal to that given
func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /dhcp/{id}/lease/{leaseID}][%d] deleteDhcpIdLeaseLeaseIdInternalServerError ", 500)
}

func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) String() string {
	return fmt.Sprintf("[DELETE /dhcp/{id}/lease/{leaseID}][%d] deleteDhcpIdLeaseLeaseIdInternalServerError ", 500)
}

func (o *DeleteDhcpIDLeaseLeaseIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
