// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDhcpIDLeaseLeaseIDParams creates a new GetDhcpIDLeaseLeaseIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDhcpIDLeaseLeaseIDParams() *GetDhcpIDLeaseLeaseIDParams {
	return &GetDhcpIDLeaseLeaseIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDhcpIDLeaseLeaseIDParamsWithTimeout creates a new GetDhcpIDLeaseLeaseIDParams object
// with the ability to set a timeout on a request.
func NewGetDhcpIDLeaseLeaseIDParamsWithTimeout(timeout time.Duration) *GetDhcpIDLeaseLeaseIDParams {
	return &GetDhcpIDLeaseLeaseIDParams{
		timeout: timeout,
	}
}

// NewGetDhcpIDLeaseLeaseIDParamsWithContext creates a new GetDhcpIDLeaseLeaseIDParams object
// with the ability to set a context for a request.
func NewGetDhcpIDLeaseLeaseIDParamsWithContext(ctx context.Context) *GetDhcpIDLeaseLeaseIDParams {
	return &GetDhcpIDLeaseLeaseIDParams{
		Context: ctx,
	}
}

// NewGetDhcpIDLeaseLeaseIDParamsWithHTTPClient creates a new GetDhcpIDLeaseLeaseIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDhcpIDLeaseLeaseIDParamsWithHTTPClient(client *http.Client) *GetDhcpIDLeaseLeaseIDParams {
	return &GetDhcpIDLeaseLeaseIDParams{
		HTTPClient: client,
	}
}

/*
GetDhcpIDLeaseLeaseIDParams contains all the parameters to send to the API endpoint

	for the get dhcp ID lease lease ID operation.

	Typically these are written to a http.Request.
*/
type GetDhcpIDLeaseLeaseIDParams struct {

	/* ID.

	   DHCP v4 server ID
	*/
	ID string

	/* LeaseID.

	   DHCP v4 lease ID
	*/
	LeaseID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dhcp ID lease lease ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDhcpIDLeaseLeaseIDParams) WithDefaults() *GetDhcpIDLeaseLeaseIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dhcp ID lease lease ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDhcpIDLeaseLeaseIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) WithTimeout(timeout time.Duration) *GetDhcpIDLeaseLeaseIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) WithContext(ctx context.Context) *GetDhcpIDLeaseLeaseIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) WithHTTPClient(client *http.Client) *GetDhcpIDLeaseLeaseIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) WithID(id string) *GetDhcpIDLeaseLeaseIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) SetID(id string) {
	o.ID = id
}

// WithLeaseID adds the leaseID to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) WithLeaseID(leaseID string) *GetDhcpIDLeaseLeaseIDParams {
	o.SetLeaseID(leaseID)
	return o
}

// SetLeaseID adds the leaseId to the get dhcp ID lease lease ID params
func (o *GetDhcpIDLeaseLeaseIDParams) SetLeaseID(leaseID string) {
	o.LeaseID = leaseID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDhcpIDLeaseLeaseIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param leaseID
	if err := r.SetPathParam("leaseID", o.LeaseID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
