// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDhcpIDParams creates a new GetDhcpIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDhcpIDParams() *GetDhcpIDParams {
	return &GetDhcpIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDhcpIDParamsWithTimeout creates a new GetDhcpIDParams object
// with the ability to set a timeout on a request.
func NewGetDhcpIDParamsWithTimeout(timeout time.Duration) *GetDhcpIDParams {
	return &GetDhcpIDParams{
		timeout: timeout,
	}
}

// NewGetDhcpIDParamsWithContext creates a new GetDhcpIDParams object
// with the ability to set a context for a request.
func NewGetDhcpIDParamsWithContext(ctx context.Context) *GetDhcpIDParams {
	return &GetDhcpIDParams{
		Context: ctx,
	}
}

// NewGetDhcpIDParamsWithHTTPClient creates a new GetDhcpIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDhcpIDParamsWithHTTPClient(client *http.Client) *GetDhcpIDParams {
	return &GetDhcpIDParams{
		HTTPClient: client,
	}
}

/*
GetDhcpIDParams contains all the parameters to send to the API endpoint

	for the get dhcp ID operation.

	Typically these are written to a http.Request.
*/
type GetDhcpIDParams struct {

	/* ID.

	   DHCP v4 server ID
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dhcp ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDhcpIDParams) WithDefaults() *GetDhcpIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dhcp ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDhcpIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dhcp ID params
func (o *GetDhcpIDParams) WithTimeout(timeout time.Duration) *GetDhcpIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dhcp ID params
func (o *GetDhcpIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dhcp ID params
func (o *GetDhcpIDParams) WithContext(ctx context.Context) *GetDhcpIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dhcp ID params
func (o *GetDhcpIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dhcp ID params
func (o *GetDhcpIDParams) WithHTTPClient(client *http.Client) *GetDhcpIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dhcp ID params
func (o *GetDhcpIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get dhcp ID params
func (o *GetDhcpIDParams) WithID(id string) *GetDhcpIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get dhcp ID params
func (o *GetDhcpIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetDhcpIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
