// Code generated by go-swagger; DO NOT EDIT.

package dhcp

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/sadov/rolctl/models"
)

// PostDhcpReader is a Reader for the PostDhcp structure.
type PostDhcpReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostDhcpReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostDhcpOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostDhcpBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostDhcpInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostDhcpOK creates a PostDhcpOK with default headers values
func NewPostDhcpOK() *PostDhcpOK {
	return &PostDhcpOK{}
}

/*
PostDhcpOK describes a response with status code 200, with default header values.

OK
*/
type PostDhcpOK struct {
	Payload *models.DtosDHCP4ServerDto
}

// IsSuccess returns true when this post dhcp o k response has a 2xx status code
func (o *PostDhcpOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post dhcp o k response has a 3xx status code
func (o *PostDhcpOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post dhcp o k response has a 4xx status code
func (o *PostDhcpOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post dhcp o k response has a 5xx status code
func (o *PostDhcpOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post dhcp o k response a status code equal to that given
func (o *PostDhcpOK) IsCode(code int) bool {
	return code == 200
}

func (o *PostDhcpOK) Error() string {
	return fmt.Sprintf("[POST /dhcp/][%d] postDhcpOK  %+v", 200, o.Payload)
}

func (o *PostDhcpOK) String() string {
	return fmt.Sprintf("[POST /dhcp/][%d] postDhcpOK  %+v", 200, o.Payload)
}

func (o *PostDhcpOK) GetPayload() *models.DtosDHCP4ServerDto {
	return o.Payload
}

func (o *PostDhcpOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosDHCP4ServerDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDhcpBadRequest creates a PostDhcpBadRequest with default headers values
func NewPostDhcpBadRequest() *PostDhcpBadRequest {
	return &PostDhcpBadRequest{}
}

/*
PostDhcpBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type PostDhcpBadRequest struct {
	Payload *models.DtosValidationErrorDto
}

// IsSuccess returns true when this post dhcp bad request response has a 2xx status code
func (o *PostDhcpBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post dhcp bad request response has a 3xx status code
func (o *PostDhcpBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post dhcp bad request response has a 4xx status code
func (o *PostDhcpBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post dhcp bad request response has a 5xx status code
func (o *PostDhcpBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post dhcp bad request response a status code equal to that given
func (o *PostDhcpBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *PostDhcpBadRequest) Error() string {
	return fmt.Sprintf("[POST /dhcp/][%d] postDhcpBadRequest  %+v", 400, o.Payload)
}

func (o *PostDhcpBadRequest) String() string {
	return fmt.Sprintf("[POST /dhcp/][%d] postDhcpBadRequest  %+v", 400, o.Payload)
}

func (o *PostDhcpBadRequest) GetPayload() *models.DtosValidationErrorDto {
	return o.Payload
}

func (o *PostDhcpBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DtosValidationErrorDto)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostDhcpInternalServerError creates a PostDhcpInternalServerError with default headers values
func NewPostDhcpInternalServerError() *PostDhcpInternalServerError {
	return &PostDhcpInternalServerError{}
}

/*
PostDhcpInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type PostDhcpInternalServerError struct {
}

// IsSuccess returns true when this post dhcp internal server error response has a 2xx status code
func (o *PostDhcpInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post dhcp internal server error response has a 3xx status code
func (o *PostDhcpInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post dhcp internal server error response has a 4xx status code
func (o *PostDhcpInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post dhcp internal server error response has a 5xx status code
func (o *PostDhcpInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post dhcp internal server error response a status code equal to that given
func (o *PostDhcpInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *PostDhcpInternalServerError) Error() string {
	return fmt.Sprintf("[POST /dhcp/][%d] postDhcpInternalServerError ", 500)
}

func (o *PostDhcpInternalServerError) String() string {
	return fmt.Sprintf("[POST /dhcp/][%d] postDhcpInternalServerError ", 500)
}

func (o *PostDhcpInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
