// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtosDeviceTemplateBootStageFileDto dtos device template boot stage file dto
//
// swagger:model dtos.DeviceTemplateBootStageFileDto
type DtosDeviceTemplateBootStageFileDto struct {

	// ExistingFileName file name is a real full file path with name on the disk.
	// This path is relative from app directory
	ExistingFileName string `json:"existingFileName,omitempty"`

	// VirtualFileName virtual file name is relative from /<mac-address>/
	VirtualFileName string `json:"virtualFileName,omitempty"`
}

// Validate validates this dtos device template boot stage file dto
func (m *DtosDeviceTemplateBootStageFileDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dtos device template boot stage file dto based on context it is used
func (m *DtosDeviceTemplateBootStageFileDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtosDeviceTemplateBootStageFileDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtosDeviceTemplateBootStageFileDto) UnmarshalBinary(b []byte) error {
	var res DtosDeviceTemplateBootStageFileDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
