// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtosEthernetSwitchVLANCreateDto dtos ethernet switch v l a n create dto
//
// swagger:model dtos.EthernetSwitchVLANCreateDto
type DtosEthernetSwitchVLANCreateDto struct {

	// TaggedPorts slice of tagged ports IDs
	TaggedPorts []string `json:"taggedPorts"`

	// UntaggedPorts slice of untagged ports IDs
	UntaggedPorts []string `json:"untaggedPorts"`

	// VlanID VLAN ID
	VlanID int64 `json:"vlanID,omitempty"`
}

// Validate validates this dtos ethernet switch v l a n create dto
func (m *DtosEthernetSwitchVLANCreateDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dtos ethernet switch v l a n create dto based on context it is used
func (m *DtosEthernetSwitchVLANCreateDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtosEthernetSwitchVLANCreateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtosEthernetSwitchVLANCreateDto) UnmarshalBinary(b []byte) error {
	var res DtosEthernetSwitchVLANCreateDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
