// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtosEthernetSwitchPortCreateDto dtos ethernet switch port create dto
//
// swagger:model dtos.EthernetSwitchPortCreateDto
type DtosEthernetSwitchPortCreateDto struct {

	// Name for this port
	Name string `json:"name,omitempty"`

	// POEEnabled POE status on a port
	Poeenabled bool `json:"poeenabled,omitempty"`

	// POEType type of PoE for this port
	// can be: "poe", "poe+", "passive24", "none"
	Poetype string `json:"poetype,omitempty"`

	// PVID default VLAN id
	Pvid int64 `json:"pvid,omitempty"`
}

// Validate validates this dtos ethernet switch port create dto
func (m *DtosEthernetSwitchPortCreateDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dtos ethernet switch port create dto based on context it is used
func (m *DtosEthernetSwitchPortCreateDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtosEthernetSwitchPortCreateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtosEthernetSwitchPortCreateDto) UnmarshalBinary(b []byte) error {
	var res DtosEthernetSwitchPortCreateDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
