// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtosEthernetSwitchModelDto dtos ethernet switch model dto
//
// swagger:model dtos.EthernetSwitchModelDto
type DtosEthernetSwitchModelDto struct {

	// Code - unique switch model code
	Code string `json:"code,omitempty"`

	// Manufacturer - Switch model manufacturer
	Manufacturer string `json:"manufacturer,omitempty"`

	// Model - Switch model
	Model string `json:"model,omitempty"`
}

// Validate validates this dtos ethernet switch model dto
func (m *DtosEthernetSwitchModelDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dtos ethernet switch model dto based on context it is used
func (m *DtosEthernetSwitchModelDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtosEthernetSwitchModelDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtosEthernetSwitchModelDto) UnmarshalBinary(b []byte) error {
	var res DtosEthernetSwitchModelDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
