// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtosHostNetworkVlanCreateDto dtos host network vlan create dto
//
// swagger:model dtos.HostNetworkVlanCreateDto
type DtosHostNetworkVlanCreateDto struct {

	// Addresses list
	Addresses []string `json:"addresses"`

	// Parent interface name
	Parent string `json:"parent,omitempty"`

	// VlanID vlan id
	VlanID int64 `json:"vlanID,omitempty"`
}

// Validate validates this dtos host network vlan create dto
func (m *DtosHostNetworkVlanCreateDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dtos host network vlan create dto based on context it is used
func (m *DtosHostNetworkVlanCreateDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtosHostNetworkVlanCreateDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtosHostNetworkVlanCreateDto) UnmarshalBinary(b []byte) error {
	var res DtosHostNetworkVlanCreateDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
