// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtosPaginationInfoDto dtos pagination info dto
//
// swagger:model dtos.PaginationInfoDto
type DtosPaginationInfoDto struct {

	// Page - page number
	Page int64 `json:"page,omitempty"`

	// Size - page size
	Size int64 `json:"size,omitempty"`

	// TotalCount - total number of items
	TotalCount int64 `json:"totalCount,omitempty"`

	// TotalPages - total number of pages
	TotalPages int64 `json:"totalPages,omitempty"`
}

// Validate validates this dtos pagination info dto
func (m *DtosPaginationInfoDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dtos pagination info dto based on context it is used
func (m *DtosPaginationInfoDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtosPaginationInfoDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtosPaginationInfoDto) UnmarshalBinary(b []byte) error {
	var res DtosPaginationInfoDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
